import java.util.Random;
import javax.swing.*;
public class Cajero extends javax.swing.JFrame {

    /** Creates new form Cajero */
    public Cajero() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Alea1 = new javax.swing.JLabel();
        Alea2 = new javax.swing.JLabel();
        Alea3 = new javax.swing.JLabel();
        Alea4 = new javax.swing.JLabel();
        Alea5 = new javax.swing.JLabel();
        Alea6 = new javax.swing.JLabel();
        Alea7 = new javax.swing.JLabel();
        Alea8 = new javax.swing.JLabel();
        Alea10 = new javax.swing.JLabel();
        Alea9 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        Proba10 = new javax.swing.JLabel();
        Proba1 = new javax.swing.JLabel();
        Proba2 = new javax.swing.JLabel();
        Proba3 = new javax.swing.JLabel();
        Proba4 = new javax.swing.JLabel();
        Proba5 = new javax.swing.JLabel();
        Proba6 = new javax.swing.JLabel();
        Proba7 = new javax.swing.JLabel();
        Proba8 = new javax.swing.JLabel();
        Proba9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Alea41 = new javax.swing.JLabel();
        Alea42 = new javax.swing.JLabel();
        Alea43 = new javax.swing.JLabel();
        Alea44 = new javax.swing.JLabel();
        Alea45 = new javax.swing.JLabel();
        Alea46 = new javax.swing.JLabel();
        Alea47 = new javax.swing.JLabel();
        Alea48 = new javax.swing.JLabel();
        Alea49 = new javax.swing.JLabel();
        Alea50 = new javax.swing.JLabel();
        Alea61 = new javax.swing.JLabel();
        Alea62 = new javax.swing.JLabel();
        Alea63 = new javax.swing.JLabel();
        Alea64 = new javax.swing.JLabel();
        Alea65 = new javax.swing.JLabel();
        Alea66 = new javax.swing.JLabel();
        Alea67 = new javax.swing.JLabel();
        Alea68 = new javax.swing.JLabel();
        Alea69 = new javax.swing.JLabel();
        Alea70 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        CC10 = new javax.swing.JLabel();
        CC1 = new javax.swing.JLabel();
        CC2 = new javax.swing.JLabel();
        CC3 = new javax.swing.JLabel();
        CC4 = new javax.swing.JLabel();
        CC5 = new javax.swing.JLabel();
        CC6 = new javax.swing.JLabel();
        CC7 = new javax.swing.JLabel();
        CC8 = new javax.swing.JLabel();
        CC9 = new javax.swing.JLabel();
        CC21 = new javax.swing.JLabel();
        CC22 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        CC23 = new javax.swing.JLabel();
        CC24 = new javax.swing.JLabel();
        CC25 = new javax.swing.JLabel();
        CC26 = new javax.swing.JLabel();
        CC37 = new javax.swing.JLabel();
        CC38 = new javax.swing.JLabel();
        CC39 = new javax.swing.JLabel();
        CC40 = new javax.swing.JLabel();
        Actualizar = new javax.swing.JButton();
        CC41 = new javax.swing.JLabel();
        CC42 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        CC43 = new javax.swing.JLabel();
        CC44 = new javax.swing.JLabel();
        CC45 = new javax.swing.JLabel();
        CC46 = new javax.swing.JLabel();
        CC57 = new javax.swing.JLabel();
        CC58 = new javax.swing.JLabel();
        CC59 = new javax.swing.JLabel();
        CC60 = new javax.swing.JLabel();
        CC61 = new javax.swing.JLabel();
        CC62 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        CC63 = new javax.swing.JLabel();
        CC64 = new javax.swing.JLabel();
        CC65 = new javax.swing.JLabel();
        CC66 = new javax.swing.JLabel();
        CC77 = new javax.swing.JLabel();
        CC78 = new javax.swing.JLabel();
        CC79 = new javax.swing.JLabel();
        CC80 = new javax.swing.JLabel();
        CC81 = new javax.swing.JLabel();
        CC82 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        CC83 = new javax.swing.JLabel();
        CC84 = new javax.swing.JLabel();
        CC85 = new javax.swing.JLabel();
        CC86 = new javax.swing.JLabel();
        CC97 = new javax.swing.JLabel();
        CC98 = new javax.swing.JLabel();
        CC99 = new javax.swing.JLabel();
        CC100 = new javax.swing.JLabel();
        CC101 = new javax.swing.JLabel();
        CC102 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        CC103 = new javax.swing.JLabel();
        CC104 = new javax.swing.JLabel();
        CC105 = new javax.swing.JLabel();
        CC106 = new javax.swing.JLabel();
        CC117 = new javax.swing.JLabel();
        CC118 = new javax.swing.JLabel();
        CC119 = new javax.swing.JLabel();
        CC120 = new javax.swing.JLabel();
        Media = new javax.swing.JTextField();
        DE = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel44.setForeground(new java.awt.Color(0, 102, 204));
        jLabel44.setText("Ensayos");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(10, 20, 40, 14);

        jLabel45.setForeground(new java.awt.Color(0, 102, 204));
        jLabel45.setText("1");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(20, 40, 20, 14);

        jLabel46.setForeground(new java.awt.Color(0, 102, 204));
        jLabel46.setText("2");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(20, 60, 20, 20);

        jLabel47.setForeground(new java.awt.Color(0, 102, 204));
        jLabel47.setText("3");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(20, 80, 20, 14);

        jLabel48.setForeground(new java.awt.Color(0, 102, 204));
        jLabel48.setText("4");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(20, 100, 20, 14);

        jLabel49.setForeground(new java.awt.Color(0, 102, 204));
        jLabel49.setText("5");
        getContentPane().add(jLabel49);
        jLabel49.setBounds(20, 120, 20, 14);

        jLabel50.setForeground(new java.awt.Color(0, 102, 204));
        jLabel50.setText("6");
        getContentPane().add(jLabel50);
        jLabel50.setBounds(20, 140, 20, 14);

        jLabel51.setForeground(new java.awt.Color(0, 102, 204));
        jLabel51.setText("7");
        getContentPane().add(jLabel51);
        jLabel51.setBounds(20, 160, 20, 14);

        jLabel52.setForeground(new java.awt.Color(0, 102, 204));
        jLabel52.setText("8");
        getContentPane().add(jLabel52);
        jLabel52.setBounds(20, 180, 20, 14);

        jLabel53.setForeground(new java.awt.Color(0, 102, 204));
        jLabel53.setText("9");
        getContentPane().add(jLabel53);
        jLabel53.setBounds(20, 200, 20, 14);

        jLabel54.setForeground(new java.awt.Color(0, 102, 204));
        jLabel54.setText("10");
        getContentPane().add(jLabel54);
        jLabel54.setBounds(20, 220, 20, 14);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("1° Aleatorios");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 62, 14);

        Alea1.setForeground(new java.awt.Color(255, 0, 0));
        Alea1.setText("0");
        getContentPane().add(Alea1);
        Alea1.setBounds(80, 40, 40, 14);

        Alea2.setForeground(new java.awt.Color(255, 0, 0));
        Alea2.setText("0");
        getContentPane().add(Alea2);
        Alea2.setBounds(80, 60, 40, 14);

        Alea3.setForeground(new java.awt.Color(255, 0, 0));
        Alea3.setText("0");
        getContentPane().add(Alea3);
        Alea3.setBounds(80, 80, 40, 14);

        Alea4.setForeground(new java.awt.Color(255, 0, 0));
        Alea4.setText("0");
        getContentPane().add(Alea4);
        Alea4.setBounds(80, 100, 40, 14);

        Alea5.setForeground(new java.awt.Color(255, 0, 0));
        Alea5.setText("0");
        getContentPane().add(Alea5);
        Alea5.setBounds(80, 120, 40, 14);

        Alea6.setForeground(new java.awt.Color(255, 0, 0));
        Alea6.setText("0");
        getContentPane().add(Alea6);
        Alea6.setBounds(80, 140, 40, 14);

        Alea7.setForeground(new java.awt.Color(255, 0, 0));
        Alea7.setText("0");
        getContentPane().add(Alea7);
        Alea7.setBounds(80, 160, 40, 14);

        Alea8.setForeground(new java.awt.Color(255, 0, 0));
        Alea8.setText("0");
        getContentPane().add(Alea8);
        Alea8.setBounds(80, 180, 40, 14);

        Alea10.setForeground(new java.awt.Color(255, 0, 0));
        Alea10.setText("0");
        getContentPane().add(Alea10);
        Alea10.setBounds(80, 220, 40, 14);

        Alea9.setForeground(new java.awt.Color(255, 0, 0));
        Alea9.setText("0");
        getContentPane().add(Alea9);
        Alea9.setBounds(80, 200, 40, 14);

        jLabel87.setForeground(new java.awt.Color(51, 204, 0));
        jLabel87.setText("Tiempo entre llegadas");
        getContentPane().add(jLabel87);
        jLabel87.setBounds(150, 20, 105, 14);

        Proba10.setForeground(new java.awt.Color(51, 204, 0));
        Proba10.setText("0");
        getContentPane().add(Proba10);
        Proba10.setBounds(150, 220, 90, 14);

        Proba1.setForeground(new java.awt.Color(51, 204, 0));
        Proba1.setText("0");
        getContentPane().add(Proba1);
        Proba1.setBounds(150, 40, 90, 14);

        Proba2.setForeground(new java.awt.Color(51, 204, 0));
        Proba2.setText("0");
        getContentPane().add(Proba2);
        Proba2.setBounds(150, 60, 90, 14);

        Proba3.setForeground(new java.awt.Color(51, 204, 0));
        Proba3.setText("0");
        getContentPane().add(Proba3);
        Proba3.setBounds(150, 80, 90, 14);

        Proba4.setForeground(new java.awt.Color(51, 204, 0));
        Proba4.setText("0");
        getContentPane().add(Proba4);
        Proba4.setBounds(150, 100, 90, 14);

        Proba5.setForeground(new java.awt.Color(51, 204, 0));
        Proba5.setText("0");
        getContentPane().add(Proba5);
        Proba5.setBounds(150, 120, 90, 14);

        Proba6.setForeground(new java.awt.Color(51, 204, 0));
        Proba6.setText("0");
        getContentPane().add(Proba6);
        Proba6.setBounds(150, 140, 90, 14);

        Proba7.setForeground(new java.awt.Color(51, 204, 0));
        Proba7.setText("0");
        getContentPane().add(Proba7);
        Proba7.setBounds(150, 160, 90, 14);

        Proba8.setForeground(new java.awt.Color(51, 204, 0));
        Proba8.setText("0");
        getContentPane().add(Proba8);
        Proba8.setBounds(150, 180, 90, 14);

        Proba9.setForeground(new java.awt.Color(51, 204, 0));
        Proba9.setText("0");
        getContentPane().add(Proba9);
        Proba9.setBounds(150, 200, 90, 14);

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("3° Aleatorios");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 20, 62, 14);

        Alea41.setForeground(new java.awt.Color(255, 0, 0));
        Alea41.setText("0");
        getContentPane().add(Alea41);
        Alea41.setBounds(680, 40, 40, 14);

        Alea42.setForeground(new java.awt.Color(255, 0, 0));
        Alea42.setText("0");
        getContentPane().add(Alea42);
        Alea42.setBounds(680, 60, 40, 14);

        Alea43.setForeground(new java.awt.Color(255, 0, 0));
        Alea43.setText("0");
        getContentPane().add(Alea43);
        Alea43.setBounds(680, 80, 40, 14);

        Alea44.setForeground(new java.awt.Color(255, 0, 0));
        Alea44.setText("0");
        getContentPane().add(Alea44);
        Alea44.setBounds(680, 100, 40, 14);

        Alea45.setForeground(new java.awt.Color(255, 0, 0));
        Alea45.setText("0");
        getContentPane().add(Alea45);
        Alea45.setBounds(680, 120, 40, 14);

        Alea46.setForeground(new java.awt.Color(255, 0, 0));
        Alea46.setText("0");
        getContentPane().add(Alea46);
        Alea46.setBounds(680, 140, 40, 14);

        Alea47.setForeground(new java.awt.Color(255, 0, 0));
        Alea47.setText("0");
        getContentPane().add(Alea47);
        Alea47.setBounds(680, 160, 40, 14);

        Alea48.setForeground(new java.awt.Color(255, 0, 0));
        Alea48.setText("0");
        getContentPane().add(Alea48);
        Alea48.setBounds(680, 180, 40, 14);

        Alea49.setForeground(new java.awt.Color(255, 0, 0));
        Alea49.setText("0");
        getContentPane().add(Alea49);
        Alea49.setBounds(680, 220, 40, 14);

        Alea50.setForeground(new java.awt.Color(255, 0, 0));
        Alea50.setText("0");
        getContentPane().add(Alea50);
        Alea50.setBounds(680, 200, 40, 14);

        Alea61.setForeground(new java.awt.Color(255, 0, 0));
        Alea61.setText("0");
        getContentPane().add(Alea61);
        Alea61.setBounds(730, 40, 40, 14);

        Alea62.setForeground(new java.awt.Color(255, 0, 0));
        Alea62.setText("0");
        getContentPane().add(Alea62);
        Alea62.setBounds(730, 60, 40, 14);

        Alea63.setForeground(new java.awt.Color(255, 0, 0));
        Alea63.setText("0");
        getContentPane().add(Alea63);
        Alea63.setBounds(730, 80, 40, 14);

        Alea64.setForeground(new java.awt.Color(255, 0, 0));
        Alea64.setText("0");
        getContentPane().add(Alea64);
        Alea64.setBounds(730, 100, 40, 14);

        Alea65.setForeground(new java.awt.Color(255, 0, 0));
        Alea65.setText("0");
        getContentPane().add(Alea65);
        Alea65.setBounds(730, 120, 40, 14);

        Alea66.setForeground(new java.awt.Color(255, 0, 0));
        Alea66.setText("0");
        getContentPane().add(Alea66);
        Alea66.setBounds(730, 140, 40, 14);

        Alea67.setForeground(new java.awt.Color(255, 0, 0));
        Alea67.setText("0");
        getContentPane().add(Alea67);
        Alea67.setBounds(730, 160, 40, 14);

        Alea68.setForeground(new java.awt.Color(255, 0, 0));
        Alea68.setText("0");
        getContentPane().add(Alea68);
        Alea68.setBounds(730, 180, 40, 14);

        Alea69.setForeground(new java.awt.Color(255, 0, 0));
        Alea69.setText("0");
        getContentPane().add(Alea69);
        Alea69.setBounds(730, 220, 40, 14);

        Alea70.setForeground(new java.awt.Color(255, 0, 0));
        Alea70.setText("0");
        getContentPane().add(Alea70);
        Alea70.setBounds(730, 200, 40, 14);

        jLabel76.setForeground(new java.awt.Color(51, 204, 0));
        jLabel76.setText("Tiempo de llegadas");
        getContentPane().add(jLabel76);
        jLabel76.setBounds(270, 20, 91, 14);

        CC10.setForeground(new java.awt.Color(51, 204, 0));
        CC10.setText("0");
        getContentPane().add(CC10);
        CC10.setBounds(270, 220, 80, 14);

        CC1.setForeground(new java.awt.Color(51, 204, 0));
        CC1.setText("0");
        getContentPane().add(CC1);
        CC1.setBounds(270, 40, 80, 14);

        CC2.setForeground(new java.awt.Color(51, 204, 0));
        CC2.setText("0");
        getContentPane().add(CC2);
        CC2.setBounds(270, 60, 80, 14);

        CC3.setForeground(new java.awt.Color(51, 204, 0));
        CC3.setText("0");
        getContentPane().add(CC3);
        CC3.setBounds(270, 80, 80, 14);

        CC4.setForeground(new java.awt.Color(51, 204, 0));
        CC4.setText("0");
        getContentPane().add(CC4);
        CC4.setBounds(270, 100, 80, 14);

        CC5.setForeground(new java.awt.Color(51, 204, 0));
        CC5.setText("0");
        getContentPane().add(CC5);
        CC5.setBounds(270, 120, 80, 14);

        CC6.setForeground(new java.awt.Color(51, 204, 0));
        CC6.setText("0");
        getContentPane().add(CC6);
        CC6.setBounds(270, 140, 80, 14);

        CC7.setForeground(new java.awt.Color(51, 204, 0));
        CC7.setText("0");
        getContentPane().add(CC7);
        CC7.setBounds(270, 160, 80, 14);

        CC8.setForeground(new java.awt.Color(51, 204, 0));
        CC8.setText("0");
        getContentPane().add(CC8);
        CC8.setBounds(270, 180, 80, 14);

        CC9.setForeground(new java.awt.Color(51, 204, 0));
        CC9.setText("0");
        getContentPane().add(CC9);
        CC9.setBounds(270, 200, 80, 14);

        CC21.setForeground(new java.awt.Color(0, 204, 204));
        CC21.setText("0");
        getContentPane().add(CC21);
        CC21.setBounds(390, 40, 80, 14);

        CC22.setForeground(new java.awt.Color(0, 204, 204));
        CC22.setText("0");
        getContentPane().add(CC22);
        CC22.setBounds(390, 60, 80, 14);

        jLabel77.setForeground(new java.awt.Color(0, 204, 204));
        jLabel77.setText("Tiempo de inicio de servicio");
        getContentPane().add(jLabel77);
        jLabel77.setBounds(390, 20, 130, 14);

        CC23.setForeground(new java.awt.Color(0, 204, 204));
        CC23.setText("0");
        getContentPane().add(CC23);
        CC23.setBounds(390, 220, 80, 14);

        CC24.setForeground(new java.awt.Color(0, 204, 204));
        CC24.setText("0");
        getContentPane().add(CC24);
        CC24.setBounds(390, 120, 80, 14);

        CC25.setForeground(new java.awt.Color(0, 204, 204));
        CC25.setText("0");
        getContentPane().add(CC25);
        CC25.setBounds(390, 80, 80, 14);

        CC26.setForeground(new java.awt.Color(0, 204, 204));
        CC26.setText("0");
        getContentPane().add(CC26);
        CC26.setBounds(390, 100, 80, 14);

        CC37.setForeground(new java.awt.Color(0, 204, 204));
        CC37.setText("0");
        getContentPane().add(CC37);
        CC37.setBounds(390, 160, 80, 14);

        CC38.setForeground(new java.awt.Color(0, 204, 204));
        CC38.setText("0");
        getContentPane().add(CC38);
        CC38.setBounds(390, 140, 80, 14);

        CC39.setForeground(new java.awt.Color(0, 204, 204));
        CC39.setText("0");
        getContentPane().add(CC39);
        CC39.setBounds(390, 200, 80, 14);

        CC40.setForeground(new java.awt.Color(0, 204, 204));
        CC40.setText("0");
        getContentPane().add(CC40);
        CC40.setBounds(390, 180, 80, 14);

        Actualizar.setText("Actualizar Todo");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Actualizar);
        Actualizar.setBounds(710, 280, 150, 30);

        CC41.setForeground(new java.awt.Color(153, 0, 153));
        CC41.setText("0");
        getContentPane().add(CC41);
        CC41.setBounds(550, 40, 80, 14);

        CC42.setForeground(new java.awt.Color(153, 0, 153));
        CC42.setText("0");
        getContentPane().add(CC42);
        CC42.setBounds(550, 60, 80, 14);

        jLabel78.setForeground(new java.awt.Color(153, 0, 153));
        jLabel78.setText("Tiempo de espera");
        getContentPane().add(jLabel78);
        jLabel78.setBounds(550, 20, 90, 14);

        CC43.setForeground(new java.awt.Color(153, 0, 153));
        CC43.setText("0");
        getContentPane().add(CC43);
        CC43.setBounds(550, 220, 80, 14);

        CC44.setForeground(new java.awt.Color(153, 0, 153));
        CC44.setText("0");
        getContentPane().add(CC44);
        CC44.setBounds(550, 120, 80, 14);

        CC45.setForeground(new java.awt.Color(153, 0, 153));
        CC45.setText("0");
        getContentPane().add(CC45);
        CC45.setBounds(550, 80, 80, 14);

        CC46.setForeground(new java.awt.Color(153, 0, 153));
        CC46.setText("0");
        getContentPane().add(CC46);
        CC46.setBounds(550, 100, 80, 14);

        CC57.setForeground(new java.awt.Color(153, 0, 153));
        CC57.setText("0");
        getContentPane().add(CC57);
        CC57.setBounds(550, 160, 80, 14);

        CC58.setForeground(new java.awt.Color(153, 0, 153));
        CC58.setText("0");
        getContentPane().add(CC58);
        CC58.setBounds(550, 140, 80, 14);

        CC59.setForeground(new java.awt.Color(153, 0, 153));
        CC59.setText("0");
        getContentPane().add(CC59);
        CC59.setBounds(550, 200, 80, 14);

        CC60.setForeground(new java.awt.Color(153, 0, 153));
        CC60.setText("0");
        getContentPane().add(CC60);
        CC60.setBounds(550, 180, 80, 14);

        CC61.setForeground(new java.awt.Color(204, 102, 0));
        CC61.setText("0");
        getContentPane().add(CC61);
        CC61.setBounds(790, 40, 80, 14);

        CC62.setForeground(new java.awt.Color(204, 102, 0));
        CC62.setText("0");
        getContentPane().add(CC62);
        CC62.setBounds(790, 60, 80, 14);

        jLabel79.setForeground(new java.awt.Color(204, 102, 0));
        jLabel79.setText("Tiempo de servicio");
        getContentPane().add(jLabel79);
        jLabel79.setBounds(790, 20, 100, 14);

        CC63.setForeground(new java.awt.Color(204, 102, 0));
        CC63.setText("0");
        getContentPane().add(CC63);
        CC63.setBounds(790, 220, 80, 14);

        CC64.setForeground(new java.awt.Color(204, 102, 0));
        CC64.setText("0");
        getContentPane().add(CC64);
        CC64.setBounds(790, 120, 80, 14);

        CC65.setForeground(new java.awt.Color(204, 102, 0));
        CC65.setText("0");
        getContentPane().add(CC65);
        CC65.setBounds(790, 80, 80, 14);

        CC66.setForeground(new java.awt.Color(204, 102, 0));
        CC66.setText("0");
        getContentPane().add(CC66);
        CC66.setBounds(790, 100, 80, 14);

        CC77.setForeground(new java.awt.Color(204, 102, 0));
        CC77.setText("0");
        getContentPane().add(CC77);
        CC77.setBounds(790, 160, 80, 14);

        CC78.setForeground(new java.awt.Color(204, 102, 0));
        CC78.setText("0");
        getContentPane().add(CC78);
        CC78.setBounds(790, 140, 80, 14);

        CC79.setForeground(new java.awt.Color(204, 102, 0));
        CC79.setText("0");
        getContentPane().add(CC79);
        CC79.setBounds(790, 200, 80, 14);

        CC80.setForeground(new java.awt.Color(204, 102, 0));
        CC80.setText("0");
        getContentPane().add(CC80);
        CC80.setBounds(790, 180, 80, 14);

        CC81.setForeground(new java.awt.Color(153, 153, 0));
        CC81.setText("0");
        getContentPane().add(CC81);
        CC81.setBounds(940, 40, 80, 14);

        CC82.setForeground(new java.awt.Color(153, 153, 0));
        CC82.setText("0");
        getContentPane().add(CC82);
        CC82.setBounds(940, 60, 80, 14);

        jLabel80.setForeground(new java.awt.Color(153, 153, 0));
        jLabel80.setText("Tiempo de terminacion");
        getContentPane().add(jLabel80);
        jLabel80.setBounds(940, 20, 130, 14);

        CC83.setForeground(new java.awt.Color(153, 153, 0));
        CC83.setText("0");
        getContentPane().add(CC83);
        CC83.setBounds(940, 220, 80, 14);

        CC84.setForeground(new java.awt.Color(153, 153, 0));
        CC84.setText("0");
        getContentPane().add(CC84);
        CC84.setBounds(940, 120, 80, 14);

        CC85.setForeground(new java.awt.Color(153, 153, 0));
        CC85.setText("0");
        getContentPane().add(CC85);
        CC85.setBounds(940, 80, 80, 14);

        CC86.setForeground(new java.awt.Color(153, 153, 0));
        CC86.setText("0");
        getContentPane().add(CC86);
        CC86.setBounds(940, 100, 80, 14);

        CC97.setForeground(new java.awt.Color(153, 153, 0));
        CC97.setText("0");
        getContentPane().add(CC97);
        CC97.setBounds(940, 160, 80, 14);

        CC98.setForeground(new java.awt.Color(153, 153, 0));
        CC98.setText("0");
        getContentPane().add(CC98);
        CC98.setBounds(940, 140, 80, 14);

        CC99.setForeground(new java.awt.Color(153, 153, 0));
        CC99.setText("0");
        getContentPane().add(CC99);
        CC99.setBounds(940, 200, 80, 14);

        CC100.setForeground(new java.awt.Color(153, 153, 0));
        CC100.setText("0");
        getContentPane().add(CC100);
        CC100.setBounds(940, 180, 80, 14);

        CC101.setText("0");
        getContentPane().add(CC101);
        CC101.setBounds(1100, 40, 80, 14);

        CC102.setText("0");
        getContentPane().add(CC102);
        CC102.setBounds(1100, 60, 80, 14);

        jLabel81.setText("Tiempo en el sistema");
        getContentPane().add(jLabel81);
        jLabel81.setBounds(1100, 20, 110, 14);

        CC103.setText("0");
        getContentPane().add(CC103);
        CC103.setBounds(1100, 220, 80, 14);

        CC104.setText("0");
        getContentPane().add(CC104);
        CC104.setBounds(1100, 120, 80, 14);

        CC105.setText("0");
        getContentPane().add(CC105);
        CC105.setBounds(1100, 80, 80, 14);

        CC106.setText("0");
        getContentPane().add(CC106);
        CC106.setBounds(1100, 100, 80, 14);

        CC117.setText("0");
        getContentPane().add(CC117);
        CC117.setBounds(1100, 160, 80, 14);

        CC118.setText("0");
        getContentPane().add(CC118);
        CC118.setBounds(1100, 140, 80, 14);

        CC119.setText("0");
        getContentPane().add(CC119);
        CC119.setBounds(1100, 200, 80, 14);

        CC120.setText("0");
        getContentPane().add(CC120);
        CC120.setBounds(1100, 180, 80, 14);

        Media.setBackground(new java.awt.Color(240, 240, 240));
        Media.setForeground(new java.awt.Color(153, 102, 255));
        Media.setBorder(javax.swing.BorderFactory.createTitledBorder("Introduce la media"));
        getContentPane().add(Media);
        Media.setBounds(300, 270, 170, 50);

        DE.setBackground(new java.awt.Color(240, 240, 240));
        DE.setForeground(new java.awt.Color(255, 0, 102));
        DE.setBorder(javax.swing.BorderFactory.createTitledBorder("Introduce Desviacion Estandar"));
        getContentPane().add(DE);
        DE.setBounds(480, 270, 180, 50);

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Calculos");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        Random rnd = new Random();
        Alea1.setText(String.valueOf(rnd.nextDouble()));
        Alea2.setText(String.valueOf(rnd.nextDouble()));
        Alea3.setText(String.valueOf(rnd.nextDouble()));
        Alea4.setText(String.valueOf(rnd.nextDouble()));
        Alea5.setText(String.valueOf(rnd.nextDouble()));
        Alea6.setText(String.valueOf(rnd.nextDouble()));
        Alea7.setText(String.valueOf(rnd.nextDouble()));
        Alea8.setText(String.valueOf(rnd.nextDouble()));
        Alea9.setText(String.valueOf(rnd.nextDouble()));
        Alea10.setText(String.valueOf(rnd.nextDouble()));
        

        double Ale1=Double.parseDouble(Alea1.getText());
        double TE=5*Ale1;
        Proba1.setText(String.valueOf(TE));
        double Prob1=Double.parseDouble(Proba1.getText());
        CC1.setText(String.valueOf(Prob1));

        double Ale2=Double.parseDouble(Alea2.getText());
        double TE1=5*Ale2;
        Proba2.setText(String.valueOf(TE1));
        double Prob2=Double.parseDouble(Proba2.getText());

        double Ale3=Double.parseDouble(Alea3.getText());
        double TE2=5*Ale3;
        Proba3.setText(String.valueOf(TE2));
        double Prob3=Double.parseDouble(Proba3.getText());

        double Ale4=Double.parseDouble(Alea4.getText());
        double TE3=5*Ale4;
        Proba4.setText(String.valueOf(TE3));
        double Prob4=Double.parseDouble(Proba4.getText());

        double Ale5=Double.parseDouble(Alea5.getText());
        double TE4=5*Ale5;
        Proba5.setText(String.valueOf(TE4));
        double Prob5=Double.parseDouble(Proba5.getText());

        double Ale6=Double.parseDouble(Alea6.getText());
        double TE5=5*Ale6;
        Proba6.setText(String.valueOf(TE5));
        double Prob6=Double.parseDouble(Proba6.getText());

        double Ale7=Double.parseDouble(Alea7.getText());
        double TE6=5*Ale7;
        Proba7.setText(String.valueOf(TE6));
        double Prob7=Double.parseDouble(Proba7.getText());

        double Ale8=Double.parseDouble(Alea8.getText());
        double TE7=5*Ale8;
        Proba8.setText(String.valueOf(TE7));
        double Prob8=Double.parseDouble(Proba8.getText());

        double Ale9=Double.parseDouble(Alea9.getText());
        double TE8=5*Ale9;
        Proba9.setText(String.valueOf(TE8));
        double Prob9=Double.parseDouble(Proba9.getText());

        double Ale10=Double.parseDouble(Alea10.getText());
        double TE9=5*Ale10;
        Proba10.setText(String.valueOf(TE9));
        double Prob10=Double.parseDouble(Proba10.getText());
//__________________________________________________________________________

        double STE=Prob1+Prob2;
        CC2.setText(String.valueOf(STE));
        double C2=Double.parseDouble(CC2.getText());
        double STE1=C2+Prob3 ;

        CC3.setText(String.valueOf(STE1));
        double C3=Double.parseDouble(CC3.getText());
        double STE2=C3+Prob4;

        CC4.setText(String.valueOf(STE2));
        double C4=Double.parseDouble(CC4.getText());
        double STE3=C4+Prob5;

        CC5.setText(String.valueOf(STE3));
        double C5=Double.parseDouble(CC5.getText());
        double STE4=C5+Prob6;

        CC6.setText(String.valueOf(STE4));
        double C6=Double.parseDouble(CC6.getText());
        double STE5=C6+Prob7;

        CC7.setText(String.valueOf(STE5));
        double C7=Double.parseDouble(CC7.getText());
        double STE6=C7+Prob8;

        CC8.setText(String.valueOf(STE6));
        double C8=Double.parseDouble(CC8.getText());
        double STE7=C8+Prob9;

        CC9.setText(String.valueOf(STE7));
        double C9=Double.parseDouble(CC9.getText());
        double STE8=C9+Prob10;

        CC10.setText(String.valueOf(STE8));
        double C10=Double.parseDouble(CC10.getText());
        double STE9=C10+Prob10;

//___________________________________________________________________


        Alea41.setText(String.valueOf(rnd.nextDouble()));
        Alea42.setText(String.valueOf(rnd.nextDouble()));
        Alea43.setText(String.valueOf(rnd.nextDouble()));
        Alea44.setText(String.valueOf(rnd.nextDouble()));
        Alea45.setText(String.valueOf(rnd.nextDouble()));
        Alea46.setText(String.valueOf(rnd.nextDouble()));
        Alea47.setText(String.valueOf(rnd.nextDouble()));
        Alea48.setText(String.valueOf(rnd.nextDouble()));
        Alea49.setText(String.valueOf(rnd.nextDouble()));
        Alea50.setText(String.valueOf(rnd.nextDouble()));
       
        Alea61.setText(String.valueOf(rnd.nextDouble()));
        Alea62.setText(String.valueOf(rnd.nextDouble()));
        Alea63.setText(String.valueOf(rnd.nextDouble()));
        Alea64.setText(String.valueOf(rnd.nextDouble()));
        Alea65.setText(String.valueOf(rnd.nextDouble()));
        Alea66.setText(String.valueOf(rnd.nextDouble()));
        Alea67.setText(String.valueOf(rnd.nextDouble()));
        Alea68.setText(String.valueOf(rnd.nextDouble()));
        Alea69.setText(String.valueOf(rnd.nextDouble()));
        Alea70.setText(String.valueOf(rnd.nextDouble()));
       

        double Ale41=Double.parseDouble(Alea41.getText());
        double Ale61=Double.parseDouble(Alea61.getText());
        double med=Double.parseDouble(Media.getText());
        double de=Double.parseDouble(DE.getText());
        double D1=(Math.sqrt(-2*Math.log(1-Ale61))*Math.sin(2*180*Ale41)*med+de);
        CC61.setText(String.valueOf(D1));

        double Ale42=Double.parseDouble(Alea42.getText());
        double Ale62=Double.parseDouble(Alea62.getText());
        double D2=(Math.sqrt(-2*Math.log(1-Ale62))*Math.cos(2*180*Ale42)*med+de);
        CC62.setText(String.valueOf(D2));

        double Ale43=Double.parseDouble(Alea43.getText());
        double Ale63=Double.parseDouble(Alea63.getText());
        double D3=(Math.sqrt(-2*Math.log(1-Ale63))*Math.sin(2*180*Ale43)*med+de);
        CC65.setText(String.valueOf(D3));

        double Ale44=Double.parseDouble(Alea44.getText());
        double Ale64=Double.parseDouble(Alea64.getText());
        double D4=(Math.sqrt(-2*Math.log(1-Ale64))*Math.cos(2*180*Ale44)*med+de);
        CC66.setText(String.valueOf(D4));

        double Ale45=Double.parseDouble(Alea45.getText());
        double Ale65=Double.parseDouble(Alea65.getText());
        double D5=(Math.sqrt(-2*Math.log(1-Ale65))*Math.sin(2*180*Ale45)*med+de);
        CC64.setText(String.valueOf(D5));

        double Ale46=Double.parseDouble(Alea46.getText());
        double Ale66=Double.parseDouble(Alea66.getText());
        double D6=(Math.sqrt(-2*Math.log(1-Ale66))*Math.cos(2*180*Ale46)*med+de);
        CC78.setText(String.valueOf(D6));

        double Ale47=Double.parseDouble(Alea47.getText());
        double Ale67=Double.parseDouble(Alea67.getText());
        double D7=(Math.sqrt(-2*Math.log(1-Ale67))*Math.sin(2*180*Ale47)*med+de);
        CC77.setText(String.valueOf(D7));

        double Ale48=Double.parseDouble(Alea48.getText());
        double Ale68=Double.parseDouble(Alea68.getText());
        double D8=(Math.sqrt(-2*Math.log(1-Ale68))*Math.cos(2*180*Ale48)*med+de);
        CC80.setText(String.valueOf(D8));

        double Ale49=Double.parseDouble(Alea49.getText());
        double Ale70=Double.parseDouble(Alea70.getText());
        double D9=(Math.sqrt(-2*Math.log(1-Ale70))*Math.sin(2*180*Ale49)*med+de);
        CC79.setText(String.valueOf(D9));

        double Ale50=Double.parseDouble(Alea50.getText());
        double Ale69=Double.parseDouble(Alea69.getText());
        double D10=(Math.sqrt(-2*Math.log(1-Ale69))*Math.cos(2*180*Ale50)*med+de);
        CC63.setText(String.valueOf(D10));
//_________________________________________________________________________

        double CCC1=Double.parseDouble(CC1.getText());
        double C61=Double.parseDouble(CC61.getText());
        CC21.setText(String.valueOf(CCC1));
        double ST=CCC1+C61;
        CC81.setText(String.valueOf(ST));

        double CCC2=Double.parseDouble(CC2.getText());
        double C62=Double.parseDouble(CC62.getText());
        CC22.setText(String.valueOf(CCC2));
        double ST1=CCC2+C62;
        CC82.setText(String.valueOf(ST1));

        double CCC3=Double.parseDouble(CC3.getText());
        double C65=Double.parseDouble(CC65.getText());
        CC25.setText(String.valueOf(CCC3));
        double ST2=CCC3+C65;
        CC85.setText(String.valueOf(ST2));

        double CCC4=Double.parseDouble(CC4.getText());
        double C66=Double.parseDouble(CC66.getText());
        CC26.setText(String.valueOf(CCC4));
        double ST3=CCC4+C66;
        CC86.setText(String.valueOf(ST3));

        double CCC5=Double.parseDouble(CC5.getText());
        double C64=Double.parseDouble(CC64.getText());
        CC24.setText(String.valueOf(CCC5));
        double ST4=CCC5+C64;
        CC84.setText(String.valueOf(ST4));

        double CCC6=Double.parseDouble(CC6.getText());
        double C78=Double.parseDouble(CC78.getText());
        CC38.setText(String.valueOf(CCC6));
        double ST5=CCC6+C78;
        CC98.setText(String.valueOf(ST5));

        double CCC7=Double.parseDouble(CC7.getText());
        double C77=Double.parseDouble(CC77.getText());
        CC37.setText(String.valueOf(CCC7));
        double ST6=CCC7+C77;
        CC97.setText(String.valueOf(ST6));

        double CCC8=Double.parseDouble(CC8.getText());
        double C80=Double.parseDouble(CC80.getText());
        CC40.setText(String.valueOf(CCC8));
        double ST7=CCC8+C80;
        CC100.setText(String.valueOf(ST7));

        double CCC9=Double.parseDouble(CC9.getText());
        double C79=Double.parseDouble(CC79.getText());
        CC39.setText(String.valueOf(CCC9));
        double ST8=CCC9+C79;
        CC99.setText(String.valueOf(ST8));

        double CCC10=Double.parseDouble(CC10.getText());
        double C63=Double.parseDouble(CC63.getText());
        CC23.setText(String.valueOf(CCC10));
        double ST9=CCC10+C63;
        CC83.setText(String.valueOf(ST9));

//__________________________________________________________

        double C81=Double.parseDouble(CC81.getText());
        double RTS=C81-CCC1;
        CC101.setText(String.valueOf(RTS));

        double C82=Double.parseDouble(CC82.getText());
        double RTS1=C82-CCC2;
        CC102.setText(String.valueOf(RTS1));

        double C85=Double.parseDouble(CC85.getText());
        double RTS2=C85-CCC3;
        CC105.setText(String.valueOf(RTS2));

        double C86=Double.parseDouble(CC86.getText());
        double RTS3=C86-CCC4;
        CC106.setText(String.valueOf(RTS3));

        double C84=Double.parseDouble(CC84.getText());
        double RTS4=C84-CCC5;
        CC104.setText(String.valueOf(RTS4));

        double C98=Double.parseDouble(CC98.getText());
        double RTS5=C98-CCC6;
        CC118.setText(String.valueOf(RTS5));

        double C97=Double.parseDouble(CC97.getText());
        double RTS6=C97-CCC7;
        CC117.setText(String.valueOf(RTS6));

        double C100=Double.parseDouble(CC100.getText());
        double RTS7=C100-CCC8;
        CC120.setText(String.valueOf(RTS7));

        double C99=Double.parseDouble(CC99.getText());
        double RTS8=C99-CCC9;
        CC119.setText(String.valueOf(RTS8));

        double C83=Double.parseDouble(CC83.getText());
        double RTS9=C83-CCC10;
        CC103.setText(String.valueOf(RTS9));




        
        


    }//GEN-LAST:event_ActualizarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JLabel Alea1;
    private javax.swing.JLabel Alea10;
    private javax.swing.JLabel Alea2;
    private javax.swing.JLabel Alea3;
    private javax.swing.JLabel Alea4;
    private javax.swing.JLabel Alea41;
    private javax.swing.JLabel Alea42;
    private javax.swing.JLabel Alea43;
    private javax.swing.JLabel Alea44;
    private javax.swing.JLabel Alea45;
    private javax.swing.JLabel Alea46;
    private javax.swing.JLabel Alea47;
    private javax.swing.JLabel Alea48;
    private javax.swing.JLabel Alea49;
    private javax.swing.JLabel Alea5;
    private javax.swing.JLabel Alea50;
    private javax.swing.JLabel Alea6;
    private javax.swing.JLabel Alea61;
    private javax.swing.JLabel Alea62;
    private javax.swing.JLabel Alea63;
    private javax.swing.JLabel Alea64;
    private javax.swing.JLabel Alea65;
    private javax.swing.JLabel Alea66;
    private javax.swing.JLabel Alea67;
    private javax.swing.JLabel Alea68;
    private javax.swing.JLabel Alea69;
    private javax.swing.JLabel Alea7;
    private javax.swing.JLabel Alea70;
    private javax.swing.JLabel Alea8;
    private javax.swing.JLabel Alea9;
    private javax.swing.JLabel CC1;
    private javax.swing.JLabel CC10;
    private javax.swing.JLabel CC100;
    private javax.swing.JLabel CC101;
    private javax.swing.JLabel CC102;
    private javax.swing.JLabel CC103;
    private javax.swing.JLabel CC104;
    private javax.swing.JLabel CC105;
    private javax.swing.JLabel CC106;
    private javax.swing.JLabel CC117;
    private javax.swing.JLabel CC118;
    private javax.swing.JLabel CC119;
    private javax.swing.JLabel CC120;
    private javax.swing.JLabel CC2;
    private javax.swing.JLabel CC21;
    private javax.swing.JLabel CC22;
    private javax.swing.JLabel CC23;
    private javax.swing.JLabel CC24;
    private javax.swing.JLabel CC25;
    private javax.swing.JLabel CC26;
    private javax.swing.JLabel CC3;
    private javax.swing.JLabel CC37;
    private javax.swing.JLabel CC38;
    private javax.swing.JLabel CC39;
    private javax.swing.JLabel CC4;
    private javax.swing.JLabel CC40;
    private javax.swing.JLabel CC41;
    private javax.swing.JLabel CC42;
    private javax.swing.JLabel CC43;
    private javax.swing.JLabel CC44;
    private javax.swing.JLabel CC45;
    private javax.swing.JLabel CC46;
    private javax.swing.JLabel CC5;
    private javax.swing.JLabel CC57;
    private javax.swing.JLabel CC58;
    private javax.swing.JLabel CC59;
    private javax.swing.JLabel CC6;
    private javax.swing.JLabel CC60;
    private javax.swing.JLabel CC61;
    private javax.swing.JLabel CC62;
    private javax.swing.JLabel CC63;
    private javax.swing.JLabel CC64;
    private javax.swing.JLabel CC65;
    private javax.swing.JLabel CC66;
    private javax.swing.JLabel CC7;
    private javax.swing.JLabel CC77;
    private javax.swing.JLabel CC78;
    private javax.swing.JLabel CC79;
    private javax.swing.JLabel CC8;
    private javax.swing.JLabel CC80;
    private javax.swing.JLabel CC81;
    private javax.swing.JLabel CC82;
    private javax.swing.JLabel CC83;
    private javax.swing.JLabel CC84;
    private javax.swing.JLabel CC85;
    private javax.swing.JLabel CC86;
    private javax.swing.JLabel CC9;
    private javax.swing.JLabel CC97;
    private javax.swing.JLabel CC98;
    private javax.swing.JLabel CC99;
    private javax.swing.JTextField DE;
    private javax.swing.JTextField Media;
    private javax.swing.JLabel Proba1;
    private javax.swing.JLabel Proba10;
    private javax.swing.JLabel Proba2;
    private javax.swing.JLabel Proba3;
    private javax.swing.JLabel Proba4;
    private javax.swing.JLabel Proba5;
    private javax.swing.JLabel Proba6;
    private javax.swing.JLabel Proba7;
    private javax.swing.JLabel Proba8;
    private javax.swing.JLabel Proba9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
