package carpinteriacarso;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author J.h
 */
public class Acceso extends javax.swing.JFrame {
    public Integer cont;
    /** Creates new form Acceso */
    public Acceso() {
        initComponents();
        final JFrame frame = new JFrame("Bienvenida");
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        frame.setVisible(false);
        SA1.setVisible(false);
        A1.setVisible(false);
        E1.setVisible(false);
        P1.setVisible(false);
        B.setVisible(false);
        Contr.setVisible(false);
        Usu.setVisible(false);
        Contr.setOpaque(false);
        Usu.setOpaque(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        SA = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        E = new javax.swing.JLabel();
        SAT = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        ET = new javax.swing.JLabel();
        PT = new javax.swing.JLabel();
        AT = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Contr = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        SA1 = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        E1 = new javax.swing.JLabel();
        P1 = new javax.swing.JLabel();
        Usu = new javax.swing.JTextField();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        Ayuda = new javax.swing.JMenu();

        jDialog1.setTitle("Bienvenida");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Metal-gold-red256.png"))); // NOI18N
        SA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SAMouseClicked(evt);
            }
        });
        getContentPane().add(SA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Metal-silver-red256.png"))); // NOI18N
        P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PMouseClicked(evt);
            }
        });
        getContentPane().add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, -1, -1));

        E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Metal-silver-blue256.png"))); // NOI18N
        E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EMouseClicked(evt);
            }
        });
        getContentPane().add(E, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        SAT.setFont(new java.awt.Font("Viner Hand ITC", 0, 36));
        SAT.setForeground(new java.awt.Color(240, 240, 240));
        SAT.setText("Super Administrador");
        getContentPane().add(SAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 350, 50));

        A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Metal-silver-green256.png"))); // NOI18N
        A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMouseClicked(evt);
            }
        });
        getContentPane().add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, -1, -1));

        ET.setFont(new java.awt.Font("Viner Hand ITC", 0, 36));
        ET.setForeground(new java.awt.Color(240, 240, 240));
        ET.setText("Empleado");
        getContentPane().add(ET, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, -1, -1));

        PT.setFont(new java.awt.Font("Viner Hand ITC", 0, 36));
        PT.setForeground(new java.awt.Color(240, 240, 240));
        PT.setText("Primer uso");
        getContentPane().add(PT, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 640, -1, -1));

        AT.setFont(new java.awt.Font("Viner Hand ITC", 0, 36));
        AT.setForeground(new java.awt.Color(240, 240, 240));
        AT.setText("Administrador");
        getContentPane().add(AT, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 250, -1));

        B.setFont(new java.awt.Font("Viner Hand ITC", 0, 36));
        B.setForeground(new java.awt.Color(240, 240, 240));
        B.setText("BIENVENIDO ");
        getContentPane().add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 240, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/go-back64.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 660, -1, -1));

        Contr.setFont(new java.awt.Font("Arial", 0, 24));
        Contr.setForeground(new java.awt.Color(240, 240, 240));
        Contr.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), new java.awt.Color(240, 240, 240))); // NOI18N
        Contr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContrActionPerformed(evt);
            }
        });
        getContentPane().add(Contr, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 240, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/salir.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 660, -1, -1));

        SA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Metal-gold-red256.png"))); // NOI18N
        SA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SA1MouseClicked(evt);
            }
        });
        getContentPane().add(SA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Metal-silver-green256.png"))); // NOI18N
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1MouseClicked(evt);
            }
        });
        getContentPane().add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Metal-silver-blue256.png"))); // NOI18N
        E1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E1MouseClicked(evt);
            }
        });
        getContentPane().add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        P1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Metal-silver-red256.png"))); // NOI18N
        P1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P1MouseClicked(evt);
            }
        });
        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        Usu.setFont(new java.awt.Font("Arial", 0, 24));
        Usu.setForeground(new java.awt.Color(240, 240, 240));
        Usu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(Usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 240, -1));
        getContentPane().add(dateChooserPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 240, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/FondoF.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu3.setText("Archivo");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Nuevo");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Actualizar");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu3);

        Ayuda.setText("Ayuda");
        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMouseClicked
        E1.setVisible(true);
        E.setVisible(false);
        SA1.setVisible(false);
        SA.setVisible(false);
        A.setVisible(false);
        A1.setVisible(false);
        E.setVisible(false);
        P.setVisible(false);
        B.setVisible(true);
        Contr.setVisible(true);
        Usu.setVisible(true);
        Contr.setOpaque(false);
        Usu.setOpaque(false);
        SAT.setVisible(false);
        AT.setVisible(false);
        ET.setVisible(false);
        PT.setVisible(false);
    }//GEN-LAST:event_EMouseClicked

    private void SAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAMouseClicked
        SA1.setVisible(true);
        SA.setVisible(false);
        A.setVisible(false);
        E.setVisible(false);
        P.setVisible(false);
        B.setVisible(true);
        Contr.setVisible(true);
        Usu.setVisible(true);
        Contr.setOpaque(false);
        Usu.setOpaque(false);
        SAT.setVisible(false);
        AT.setVisible(false);
        ET.setVisible(false);
        PT.setVisible(false);
    }//GEN-LAST:event_SAMouseClicked

    private void AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMouseClicked
        A1.setVisible(true);
        A.setVisible(false);
        SA1.setVisible(false);
        SA.setVisible(false);
        A.setVisible(false);
        E.setVisible(false);
        P.setVisible(false);
        B.setVisible(true);
        Contr.setVisible(true);
        Usu.setVisible(true);
        Contr.setOpaque(false);
        Usu.setOpaque(false);
        SAT.setVisible(false);
        AT.setVisible(false);
        ET.setVisible(false);
        PT.setVisible(false);
    }//GEN-LAST:event_AMouseClicked

    private void PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PMouseClicked
        P1.setVisible(true);
        P.setVisible(false);
        E1.setVisible(false);
        E.setVisible(false);
        SA1.setVisible(false);
        SA.setVisible(false);
        A.setVisible(false);
        A1.setVisible(false);
        E.setVisible(false);
        P.setVisible(false);
        B.setVisible(true);
        Contr.setVisible(true);
        Usu.setVisible(true);
        Contr.setOpaque(false);
        Usu.setOpaque(false);
        SAT.setVisible(false);
        AT.setVisible(false);
        ET.setVisible(false);
        PT.setVisible(false);
    }//GEN-LAST:event_PMouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        new Bienvenida().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int res = JOptionPane.showConfirmDialog( this,"¿Esta Usted Seguro de Salir del Sistema Carpiteria Carso?",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.YES_OPTION ) {
            JOptionPane.showMessageDialog(rootPane,"Gracias por usar el sistema");
            new Salir().setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void SA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SA1MouseClicked
      String usu=Usu.getText();
      String pass=Contr.getText();
        if(usu.equals("Joel")&& pass.equals("123")|| usu.equals("Omar")&& pass.equals("isaias")){
         JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
        new Menu().setVisible(true);
           this.dispose();
         }else {
            JOptionPane.showMessageDialog(this,"Contraseña Incorrecta");
            Usu.setText("");
            Contr.setText("");
            Usu.requestFocus();
            cont++;
        }
        if(cont>=3){
            JOptionPane.showMessageDialog(this,"Se excedio intente mas tarde");
            new Salir().setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_SA1MouseClicked

    private void A1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseClicked
         String usu=Usu.getText();
      String pass=Contr.getText();
        if(usu.equals("Joel")&& pass.equals("123")|| usu.equals("Omar")&& pass.equals("isaias")){
         JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
        new Menu().setVisible(true);
           this.dispose();
         }else {
            JOptionPane.showMessageDialog(this,"Contraseña Incorrecta");
            Usu.setText("");
            Contr.setText("");
            Usu.requestFocus();
            cont++;
        }
        if(cont>=3){
            JOptionPane.showMessageDialog(this,"Se excedio intente mas tarde");
            new Salir().setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_A1MouseClicked

    private void E1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E1MouseClicked
      String usu=Usu.getText();
      String pass=Contr.getText();
        if(usu.equals("Joel")&& pass.equals("123")|| usu.equals("Omar")&& pass.equals("isaias")){
         JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
        new Menu().setVisible(true);
           this.dispose();
         }else {
            JOptionPane.showMessageDialog(this,"Contraseña Incorrecta");
            Usu.setText("");
            Contr.setText("");
            Usu.requestFocus();
            cont++;
        }
        if(cont>=3){
            JOptionPane.showMessageDialog(this,"Se excedio intente mas tarde");
            new Salir().setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_E1MouseClicked

    private void P1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P1MouseClicked
      String usu=Usu.getText();
      String pass=Contr.getText();
        if(usu.equals("Joel")&& pass.equals("123")|| usu.equals("Omar")&& pass.equals("isaias")){
         JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
        new Menu().setVisible(true);
           this.dispose();
         }else {
            JOptionPane.showMessageDialog(this,"Contraseña Incorrecta");
            Usu.setText("");
            Contr.setText("");
            Usu.requestFocus();
            cont++;
        }
        if(cont>=3){
            JOptionPane.showMessageDialog(this,"Se excedio intente mas tarde");
            new Salir().setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_P1MouseClicked

    private void ContrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContrActionPerformed
        String U=Usu.getText();
      String C=Contr.getText();
        if(U.equals("Joel") && C.equals("123")|| U.equals("Omar")&& C.equals("isaias")){
         JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
        new Menu().setVisible(true);
           this.dispose();
         }else {
            JOptionPane.showMessageDialog(this,"Contraseña Incorrecta");
            Usu.setText("");
            Contr.setText("");
            Usu.requestFocus();
            cont++;
        }
        if(cont>=3){
            JOptionPane.showMessageDialog(this,"Se excedio intente mas tarde");
            new Salir().setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_ContrActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        new Acceso().setVisible(true);
        this.dispose();
}//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        new Acceso().setVisible(true);
        this.dispose();
}//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel A1;
    private javax.swing.JLabel AT;
    private javax.swing.JMenu Ayuda;
    private javax.swing.JLabel B;
    private javax.swing.JPasswordField Contr;
    private javax.swing.JLabel E;
    private javax.swing.JLabel E1;
    private javax.swing.JLabel ET;
    private javax.swing.JLabel P;
    private javax.swing.JLabel P1;
    private javax.swing.JLabel PT;
    private javax.swing.JLabel SA;
    private javax.swing.JLabel SA1;
    private javax.swing.JLabel SAT;
    private javax.swing.JTextField Usu;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
