package carpinteriacarso;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Calendar;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author J.h
 */
public class Clientes extends javax.swing.JFrame {
    DefaultTableModel modelo;
    public Connection conexion;
    public Statement sentencia;
    public ResultSet resultado;
    public String Nombre1,Registro,Operacion;
    public Integer Contrasena,cont;
    public FileInputStream fis;
    public int longitudBytes;

    /** Creates new form Clientes */
    public Clientes() {
        initComponents();
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        FalloEnlace.setVisible(false);
        TextoFallo.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
        Otro.setVisible(false);
        Folio.setOpaque(false);
        Nombre.setOpaque(false);
        Edad.setOpaque(false);
        Direccion.setOpaque(false);
        RFC.setOpaque(false);
        Email.setOpaque(false);
        Telefono.setOpaque(false);
        Promo.setOpaque(false);
        Des.setOpaque(false);
        Pago1.setOpaque(false);
        Sexo.setOpaque(false);
        Otro.setOpaque(false);
        Tabla.setOpaque(false);
        String Cabecera[]={"Consultor","Fecha","Hora","Operacion","Folio","Nombre","Edad","Dirección","RFC","Email","Telefono","Promocion","Descuento","Pago","Sexo"};
        String Datos [][]={};
        modelo=new DefaultTableModel(Datos,Cabecera);
        Tabla.setModel(modelo);

        Toolkit t=Toolkit.getDefaultToolkit();
        setIconImage(t.getImage(getClass().getResource("/carpinteriacarso/imagenes/log.jpg")));

         setTitle("Cliente");
         Calendar cal=Calendar.getInstance();
          String fecha=cal.get(cal.DATE)+"/"+cal.get(cal.MONTH)+"/"+cal.get(cal.YEAR);
          String hora=cal.get(cal.HOUR_OF_DAY)+":"+cal.get(cal.MINUTE)+":"+cal.get(cal.SECOND);
          this.Fecha.setText(fecha);
          this.Hora.setText(hora);
          JOptionPane.showMessageDialog(rootPane,"Acceso: "+fecha+ ".... A la Hora: "+hora);
          JOptionPane.showMessageDialog(rootPane,"Datos Almacenados");
          String Nom = JOptionPane.showInputDialog(rootPane, "Introduce tu Nombre");
        Registro = String.valueOf(String.valueOf(Nom));
        Nombre2.setText(String.valueOf(Registro));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        Folio = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        RFC = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Promocion = new javax.swing.JComboBox();
        Descuentos = new javax.swing.JComboBox();
        Pago = new javax.swing.JComboBox();
        Telefono = new javax.swing.JTextField();
        Promo = new javax.swing.JLabel();
        Des = new javax.swing.JLabel();
        Se = new javax.swing.JComboBox();
        Pago1 = new javax.swing.JLabel();
        Sexo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Edad = new javax.swing.JTextField();
        ImagenG = new javax.swing.JLabel();
        TextoG = new javax.swing.JLabel();
        FalloEnlace = new javax.swing.JLabel();
        TextoFallo = new javax.swing.JLabel();
        ConExi = new javax.swing.JLabel();
        TextoExi = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Otro = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Ope = new javax.swing.JLabel();
        Foto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        His = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        Imagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        Ayuda = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 0, 48));
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Clientes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 190, 60));

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Altas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 70, 40));

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Bajas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 70, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Bajas.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Consultas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Consultas.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        jLabel9.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Guardar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Actualizar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Altas.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Modificar");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 80, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Actualizar.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Modificar.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 120, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Guardar.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/go-back64.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 610, -1, -1));

        Fecha.setFont(new java.awt.Font("Viner Hand ITC", 0, 18));
        Fecha.setForeground(new java.awt.Color(240, 240, 240));
        Fecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de Acceso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 150, 60));

        Hora.setFont(new java.awt.Font("Viner Hand ITC", 0, 18));
        Hora.setForeground(new java.awt.Color(240, 240, 240));
        Hora.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora de Acceso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 140, 60));

        Folio.setBackground(new java.awt.Color(0, 0, 0));
        Folio.setFont(new java.awt.Font("Arial", 0, 18));
        Folio.setForeground(new java.awt.Color(240, 240, 240));
        Folio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Folio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(240, 240, 240))); // NOI18N
        Folio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FolioActionPerformed(evt);
            }
        });
        Folio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FolioKeyTyped(evt);
            }
        });
        getContentPane().add(Folio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 90, 40));

        Nombre.setBackground(new java.awt.Color(0, 0, 0));
        Nombre.setFont(new java.awt.Font("Arial", 0, 18));
        Nombre.setForeground(new java.awt.Color(240, 240, 240));
        Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre Completo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(240, 240, 240))); // NOI18N
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 430, -1));

        Direccion.setBackground(new java.awt.Color(0, 0, 0));
        Direccion.setFont(new java.awt.Font("Arial", 0, 18));
        Direccion.setForeground(new java.awt.Color(240, 240, 240));
        Direccion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(240, 240, 240))); // NOI18N
        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DireccionKeyTyped(evt);
            }
        });
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 430, -1));

        RFC.setBackground(new java.awt.Color(0, 0, 0));
        RFC.setFont(new java.awt.Font("Arial", 0, 18));
        RFC.setForeground(new java.awt.Color(240, 240, 240));
        RFC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RFC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(240, 240, 240))); // NOI18N
        RFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFCActionPerformed(evt);
            }
        });
        RFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RFCKeyTyped(evt);
            }
        });
        getContentPane().add(RFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 430, -1));

        Email.setBackground(new java.awt.Color(0, 0, 0));
        Email.setFont(new java.awt.Font("Arial", 0, 18));
        Email.setForeground(new java.awt.Color(240, 240, 240));
        Email.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(240, 240, 240))); // NOI18N
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailKeyTyped(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 430, -1));

        Promocion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Con Promocion", "Sin Promocion" }));
        Promocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PromocionActionPerformed(evt);
            }
        });
        getContentPane().add(Promocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 120, -1));

        Descuentos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Descuento", "Sin descuento" }));
        getContentPane().add(Descuentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 110, -1));

        Pago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tarjeta", "Efectivo" }));
        Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagoActionPerformed(evt);
            }
        });
        getContentPane().add(Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 80, -1));

        Telefono.setBackground(new java.awt.Color(0, 0, 0));
        Telefono.setFont(new java.awt.Font("Arial", 0, 18));
        Telefono.setForeground(new java.awt.Color(240, 240, 240));
        Telefono.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(240, 240, 240))); // NOI18N
        Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 430, -1));

        Promo.setFont(new java.awt.Font("Arial", 0, 18));
        Promo.setForeground(new java.awt.Color(240, 240, 240));
        Promo.setText("Promoción");
        Promo.setToolTipText("");
        getContentPane().add(Promo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 120, 20));

        Des.setFont(new java.awt.Font("Arial", 0, 18));
        Des.setForeground(new java.awt.Color(240, 240, 240));
        Des.setText("Descuento");
        getContentPane().add(Des, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 110, 20));

        Se.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        getContentPane().add(Se, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 90, -1));

        Pago1.setFont(new java.awt.Font("Arial", 0, 18));
        Pago1.setForeground(new java.awt.Color(240, 240, 240));
        Pago1.setText("Pago");
        getContentPane().add(Pago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 80, 20));

        Sexo.setFont(new java.awt.Font("Arial", 0, 18));
        Sexo.setForeground(new java.awt.Color(240, 240, 240));
        Sexo.setText("Sexo");
        getContentPane().add(Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, 90, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Vaciar.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, -1, -1));

        Edad.setBackground(new java.awt.Color(0, 0, 0));
        Edad.setFont(new java.awt.Font("Arial", 0, 18));
        Edad.setForeground(new java.awt.Color(240, 240, 240));
        Edad.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(240, 240, 240))); // NOI18N
        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });
        Edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EdadKeyTyped(evt);
            }
        });
        getContentPane().add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 180, -1));

        ImagenG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/AgregadoExi.png"))); // NOI18N
        getContentPane().add(ImagenG, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 140, -1));

        TextoG.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        TextoG.setForeground(new java.awt.Color(240, 240, 240));
        TextoG.setText("Dato Agregado Exitosamente");
        getContentPane().add(TextoG, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        FalloEnlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Fallo Enlace.png"))); // NOI18N
        getContentPane().add(FalloEnlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 140, -1));

        TextoFallo.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        TextoFallo.setForeground(new java.awt.Color(240, 240, 240));
        TextoFallo.setText("Error de enlace con la Base de Datos");
        getContentPane().add(TextoFallo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 400, 30));

        ConExi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/ConsultaExitosa.png"))); // NOI18N
        getContentPane().add(ConExi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, -1, -1));

        TextoExi.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        TextoExi.setForeground(new java.awt.Color(240, 240, 240));
        TextoExi.setText("Consulta Exitosa");
        getContentPane().add(TextoExi, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 200, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/salir.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel17MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 610, -1, -1));

        Nombre2.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        Nombre2.setForeground(new java.awt.Color(240, 240, 240));
        Nombre2.setText("Registro");
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 350, 40));

        jLabel18.setFont(new java.awt.Font("Viner Hand ITC", 0, 36));
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Bienvenido");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 200, 60));

        Tabla.setBackground(new java.awt.Color(240, 240, 240));
        Tabla.setFont(new java.awt.Font("Arial", 0, 12));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Otro.setViewportView(Tabla);

        getContentPane().add(Otro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 1150, 140));

        Ope.setFont(new java.awt.Font("Arial", 0, 18));
        Ope.setForeground(new java.awt.Color(240, 240, 240));
        Ope.setText("Operacion");
        getContentPane().add(Ope, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, -1, -1));

        Foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Foto.png"))); // NOI18N
        Foto.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        Foto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FotoMouseClicked(evt);
            }
        });
        getContentPane().add(Foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 110, 250, 310));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Tu foto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 80, -1, -1));

        His.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        His.setForeground(new java.awt.Color(240, 240, 240));
        His.setText("Historial");
        getContentPane().add(His, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 110, -1));
        getContentPane().add(dateChooserCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, -1, -1));

        Imagen.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Fon5T.jpg"))); // NOI18N
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu3.setText("Archivo");

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Nuevo");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Actualizar");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu3);

        Ayuda.setText("Ayuda");
        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       // Altas
        //Folio.disable();//DESHABILITAR LA CAJA DE TEXTO DE BUSCAR
        String O = JOptionPane.showInputDialog(rootPane, "Introduce la Accion a Realizar");
        Operacion = String.valueOf(String.valueOf(O));
        Ope.setText(String.valueOf(Operacion));
        int res = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
            new Clientes().setVisible(true);
        this.dispose();
        }
        if( res == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));
        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
        Folio.setText("");
        //HABILITAR TODOS LOS TEXTFIELDS PARA EL INGRESO DE DATOS
        Nombre.enable(true);
        Edad.enable(true);
        Direccion.enable(true);
        RFC.enable(true);
        Email.enable(true);
        Telefono.enable(true);
        Promo.enable(true);
        Des.enable(true);
        Pago1.enable(true);
        Sexo.enable(true);
        Otro.setVisible(true);
         String F=Folio.getText();
                String Op=Ope.getText();
                String N=Nombre.getText();
                String E=Edad.getText();
                String D=Direccion.getText();
                String R=RFC.getText();
                String M=Email.getText();
                String T=Telefono.getText();
                String P=Promocion.getSelectedItem().toString();
                String De=Descuentos.getSelectedItem().toString();
                String Pa=Pago.getSelectedItem().toString();
                String S=Se.getSelectedItem().toString();
                String H=Hora.getText();
                String Fe=Fecha.getText();
                String No=Nombre2.getText();
                Object Datos[]={No,Fe,H,Op,F,N,E,D,R,M,T,P,De,Pa,S};
                modelo.addRow(Datos);

        //Se limpia cajas de texto
        Nombre.setText("");
        Edad.setText("");
        Direccion.setText("");
        RFC.setText("");
        Email.setText("");
        Telefono.setText("");
        Promo.setText("");
        Des.setText("");
        Pago1.setText("");
        Sexo.setText("");
        }}
        //FINALIZACION DE LIMPIEZA DE CAJAS DE TEXTO
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // Bajas
        try {
            Class.forName(  "com.mysql.jdbc.Driver" );
        } catch( Exception eve ) {
            JOptionPane.showMessageDialog(null,"Fallo Enlace, Sistema ");
            FalloEnlace.setVisible(true);
            TextoFallo.setVisible(true);
            ImagenG.setVisible(false);
        TextoG.setVisible(false);
        FalloEnlace.setVisible(false);
        ConExi.setVisible(false);
            return;
        }
        try{
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/cc","root", "123");
            sentencia=conexion.createStatement();

        String O = JOptionPane.showInputDialog(rootPane, "Introduce la Accion a Realizar");
        Operacion = String.valueOf(String.valueOf(O));
        Ope.setText(String.valueOf(Operacion));

       int res1 = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
       "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );

        if( res1 == JOptionPane.NO_OPTION ) {
        JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
        new Clientes().setVisible(true);
        this.dispose();
        }


        if( res1 == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));


        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");

             int res = JOptionPane.showConfirmDialog( this,"¿Esta Usted Seguro de dar de Baja",
             "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(null,"Baja Cancelada...!!!");
            sentencia.execute("DELETE FROM clientes WHERE Id_Cliente = "+Folio.getText());
            sentencia.close();
        }
           if( res == JOptionPane.YES_OPTION ) {
               Otro.setVisible(true);
                String Op=Ope.getText();
                String F=Folio.getText();
                String N=Nombre.getText();
                String E=Edad.getText();
                String D=Direccion.getText();
                String R=RFC.getText();
                String M=Email.getText();
                String T=Telefono.getText();
                String P=Promocion.getSelectedItem().toString();
                String De=Descuentos.getSelectedItem().toString();
                String Pa=Pago.getSelectedItem().toString();
                String S=Se.getSelectedItem().toString();
                String H=Hora.getText();
                String Fe=Fecha.getText();
                String No=Nombre2.getText();
                Object Datos[]={No,Fe,H,Op,F,N,E,D,R,M,T,P,De,Pa,S};
                modelo.addRow(Datos);
            Nombre.setText("");
            Edad.setText("");
            Direccion.setText("");
            RFC.setText("");
            Email.setText("");
            Telefono.setText("");
            Promo.setText("");
            Des.setText("");
            Pago1.setText("");
            Sexo.setText("");
            }}}
        } catch(SQLException x){JOptionPane.showMessageDialog(null,"Fallo Enlace, Sistema  ");
        FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       // Consultar
        
        try  {
            Class.forName( "com.mysql.jdbc.Driver" );
        } catch( Exception eve ) {
            JOptionPane.showMessageDialog(null,"Error en el Enlace, Sistema ");
            FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoFallo.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
            return;
        }
        try{
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/cc","root", "123");
            sentencia=conexion.createStatement();
             String O = JOptionPane.showInputDialog(rootPane, "Introduce la Accion a Realizar");
        Operacion = String.valueOf(String.valueOf(O));
        Ope.setText(String.valueOf(Operacion));
            int res = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
            new Clientes().setVisible(true);
        this.dispose();
        }
        if( res == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));
        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
            resultado=sentencia.executeQuery("SELECT * FROM clientes WHERE Id_Cliente =" + Folio.getText());
            if (resultado.next()){
                
                
                Nombre.setText(String.valueOf(resultado.getString(2)));
                Edad.setText(String.valueOf(resultado.getString(3)));
                Direccion.setText(String.valueOf(resultado.getString(4)));
                RFC.setText(String.valueOf(resultado.getString(5)));
                Email.setText(String.valueOf(resultado.getString(6)));
                Telefono.setText(String.valueOf(resultado.getString(7)));
                Promo.setText(String.valueOf(resultado.getString(8)));
                Des.setText(String.valueOf(resultado.getString(9)));
                Pago1.setText(String.valueOf(resultado.getString(10)));
                Sexo.setText(String.valueOf(resultado.getString(11)));
                String Op=Ope.getText();
                String F=Folio.getText();
                String N=Nombre.getText();
                String E=Edad.getText();
                String D=Direccion.getText();
                String R=RFC.getText();
                String M=Email.getText();
                String T=Telefono.getText();
                String P=Promocion.getSelectedItem().toString();
                String De=Descuentos.getSelectedItem().toString();
                String Pa=Pago.getSelectedItem().toString();
                String S=Se.getSelectedItem().toString();
                String H=Hora.getText();
                String Fe=Fecha.getText();
               String No=Nombre2.getText();
                Object Datos[]={No,Fe,H,Op,F,N,E,D,R,M,T,P,De,Pa,S};
                modelo.addRow(Datos);
//                Folio.setText("");
//                Nombre.setText("");
//            Edad.setText("");
//            Direccion.setText("");
//            RFC.setText("");
//            Email.setText("");
//            Telefono.setText("");
//            Promo.setText("");
//            Des.setText("");
//            Pago1.setText("");
//            Sexo.setText("");
                Otro.setVisible(true);
                TextoExi.setVisible(true);
                ConExi.setVisible(true);
                ImagenG.setVisible(false);
                TextoG.setVisible(false);
                FalloEnlace.setVisible(false);
                TextoFallo.setVisible(false);
                Tabla.setVisible(true);
                sentencia.close();
            } else {
                JOptionPane.showMessageDialog(null,"No existe el Empleado ");
            }}}
        } catch(SQLException exp){
        JOptionPane.showMessageDialog(null,"Error en la Conexion, Sistema ");
        FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // Guardar
if(Folio.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo Folio esta vacio");
 }
if(Nombre.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo Nombre está vacío ");
 }
if(Edad.getText().trim().length()==0)
 {
 JOptionPane.showMessageDialog(this, "El campo de Edad está vacío ");
 }
if(Direccion.getText().trim().length()==0)
 {
 JOptionPane.showMessageDialog(this, "El campo de Direccion está vacío ");
 }
if(RFC.getText().trim().length()==0)
 {
 JOptionPane.showMessageDialog(this, "El campo de RFC está vacío ");
 }
if(Email.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Email está vacío ");
 }
if(Telefono.getText().trim().length()==0)
 {
 JOptionPane.showMessageDialog(this, "El campo de Telefono está vacío ");
 }
if(Promo.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Promocion está vacío ");
 }
if(Des.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Descuento está vacío ");
 }
if(Pago1.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Tipo de Pago está vacío ");
 }
if(Sexo.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Sexo está vacío ");
 }
if(Hora.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Hora está vacío ");
 }
  if(Fecha.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Fecha está vacío ");
 }
        try {
            Class.forName(  "com.mysql.jdbc.Driver" );
        } catch( Exception eve ) {
            JOptionPane.showMessageDialog(null,"Fallo Enlace del Puente, Sistema"+eve);
            FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
            return;
        }
        if(Nombre.getText()=="") {
            Nombre.setText("");
        }
        if(Edad.getText()=="") {
            Edad.setText("");
        }
      if(Direccion.getText()=="") {
            Direccion.setText("");
        }
        if(RFC.getText()=="") {
            RFC.setText("");
        }
        if(Email.getText()=="") {
            Email.setText("");
        }
        if(Telefono.getText()=="") {
            Telefono.setText("");
        }
        if(Promo.getText()=="") {
            Promo.setText("");
        }
        if(Des.getText()=="") {
            Des.setText("");
        }
        if(Pago1.getText()=="") {
            Pago1.setText("");
        }
        if(Sexo.getText()=="") {
            Sexo.setText("");
        }
        if(Hora.getText()=="") {
            Hora.setText("");
        }
        if(Fecha.getText()=="") {
            Fecha.setText("");
        }
        try{
        String O = JOptionPane.showInputDialog(rootPane, "Introduce la Accion a Realizar");
        Operacion = String.valueOf(String.valueOf(O));
        Ope.setText(String.valueOf(Operacion));
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/cc","root", "123");
            sentencia=conexion.createStatement();
            sentencia.executeUpdate("INSERT INTO clientes"+
                    " VALUES ('"+Folio.getText()+"',"+
                    "'"+Nombre.getText()+"',"+
                    "'"+Edad.getText()+"',"+
                    "'"+Direccion.getText()+"',"+
                    "'"+RFC.getText()+"',"+
                    "'"+Email.getText()+"',"+
                    "'"+Telefono.getText()+"',"+
                    "'"+Promo.getText()+"',"+
                    "'"+Des.getText()+"',"+
                    "'"+Pago1.getText()+"',"+
                    "'"+Sexo.getText()+"',"+
                    "'"+Hora.getText()+"',"+
                    "'"+Fecha.getText()+"')");
                Otro.setVisible(true);
                String Op=Ope.getText();
                String F=Folio.getText();
                String N=Nombre.getText();
                String E=Edad.getText();
                String D=Direccion.getText();
                String R=RFC.getText();
                String M=Email.getText();
                String T=Telefono.getText();
                String P=Promocion.getSelectedItem().toString();
                String De=Descuentos.getSelectedItem().toString();
                String Pa=Pago.getSelectedItem().toString();
                String S=Se.getSelectedItem().toString();
                String H=Hora.getText();
                String Fe=Fecha.getText();
                String No=Nombre2.getText();
                Object Datos[]={No,Fe,H,Op,F,N,E,D,R,M,T,P,De,Pa,S};
                modelo.addRow(Datos);

            Folio.setText("");
            Nombre.setText("");
            Edad.setText("");
            Direccion.setText("");
            RFC.setText("");
            Email.setText("");
            Telefono.setText("");
            Promo.setText("");
            Des.setText("");
            Pago1.setText("");
            Sexo.setText("");
                
            conexion.close();
            JOptionPane.showMessageDialog(null,"Cliente Guardado ");
            ImagenG.setVisible(true);
        TextoG.setVisible(true);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
         FalloEnlace.setVisible(false);
        TextoFallo.setVisible(false);
        } catch(SQLException p){ JOptionPane.showMessageDialog(null,"Error en el enlace, Sistema"+p);
        FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);}
        
//        //LIMPIAR CAJA DE TEXTO UNA VEZ GUARDADA LA INFORMACION.
//         Folio.setText("");
//         Nombre.setText("");
//         IniciodeOperacion.setText("");
//         Edad.setText("");
//         Sexo.setText("");
//         Puesto.setText("");
//         Salario.setText("");
//         CP.setText("");
//         Calle.setText("");
//         Colonia.setText("");
//         Mz.setText("");
//         Lt.setText("");
//         TP.setText("");
//         TC.setText("");
//         TR.setText("");
//         Email.setText("");
//         curp.setText("");
//        //HABILITAR LA CAJA DE TEXTO DE BUSCAR.
        Folio.enable();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        try  {
            Class.forName( "com.mysql.jdbc.Driver" );
        } catch( Exception eve ) {
            JOptionPane.showMessageDialog(null,"Error en el Enlace, Sistema ");
            FalloEnlace.setVisible(true);
            TextoFallo.setVisible(true);
            ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
            return;
        }
        try{
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/cc","root", "123");
            sentencia=conexion.createStatement();
             String O = JOptionPane.showInputDialog(rootPane, "Introduce la Accion a Realizar");
        Operacion = String.valueOf(String.valueOf(O));
        Ope.setText(String.valueOf(Operacion));
             int res = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
            new Clientes().setVisible(true);
        this.dispose();
        }
        if( res == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));
        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
            sentencia.execute("UPDATE clientes SET Nombre=('"+Nombre.getText()+"'),"
                    + "Edad=("+Edad.getText()+"),"
                    + "Direccion=('"+Direccion.getText()+"'),"
                    + "RFC=('"+RFC.getText()+"'),"
                    + "Email=('"+Email.getText()+"'),"
                    + "Telefono=("+Telefono.getText()+"),"
                    + "Promo=('"+Promo.getText()+"'),"
                    + "Des=('"+Des.getText()+"'),"
                    + "Pago1=('"+Pago1.getText()+"'),"
                    + "Sexo=('"+Sexo.getText()+"')"
                    + " WHERE Id_Cliente=" + Folio.getText());
            Otro.setVisible(true);
             String Op=Ope.getText();
             String F=Folio.getText();
                String N=Nombre.getText();
                String E=Edad.getText();
                String D=Direccion.getText();
                String R=RFC.getText();
                String M=Email.getText();
                String T=Telefono.getText();
                String P=Promocion.getSelectedItem().toString();
                String De=Descuentos.getSelectedItem().toString();
                String Pa=Pago.getSelectedItem().toString();
                String S=Se.getSelectedItem().toString();
              String H=Hora.getText();
                String Fe=Fecha.getText();
                String No=Nombre2.getText();
                Object Datos[]={No,Fe,H,Op,F,N,E,D,R,M,T,P,De,Pa,S};
                modelo.addRow(Datos);
            JOptionPane.showMessageDialog(null,"Cambios Realizados, Registro Guardado ");
        }}
            sentencia.close();
        } catch (SQLException e2){
            JOptionPane.showMessageDialog(null,"Fallo Enlace, Sistema "+e2);
         FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
        }
        
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // Modificar
//        Menu.setEnabled(false);
//        Modificar.setEnabled(false);
//        Guardar.setEnabled(false);
//        Actualizar.setVisible(true);//se pone accesible el boton de guardar cambios
        //habilitar cajas de Texto
         String O = JOptionPane.showInputDialog(rootPane, "Introduce la Accion a Realizar");
        Operacion = String.valueOf(String.valueOf(O));
        Ope.setText(String.valueOf(Operacion));
        int res = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
            new Clientes().setVisible(true);
        this.dispose();
        }
        if( res == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));
        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
        Nombre.enable(true);
        Edad.enable(true);
        Direccion.enable(true);
        RFC.enable(true);
        Email.enable(true);
        Telefono.enable(true);
        Promo.enable(true);
        Des.enable(true);
        Pago1.enable(true);
        Sexo.enable(true);
        Otro.setVisible(true);
         String Op=Ope.getText();
         String F=Folio.getText();
                String N=Nombre.getText();
                String E=Edad.getText();
                String D=Direccion.getText();
                String R=RFC.getText();
                String M=Email.getText();
                String T=Telefono.getText();
                String P=Promocion.getSelectedItem().toString();
                String De=Descuentos.getSelectedItem().toString();
                String Pa=Pago.getSelectedItem().toString();
                String S=Se.getSelectedItem().toString();
               String H=Hora.getText();
                String Fe=Fecha.getText();
                String No=Nombre2.getText();
                Object Datos[]={No,Fe,H,Op,F,N,E,D,R,M,T,P,De,Pa,S};
                modelo.addRow(Datos);
        }
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
       new Menu().setVisible(true);
        JOptionPane.showMessageDialog(rootPane,"Guardando Cambios Necesarios");
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void FolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FolioActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_FolioActionPerformed

    private void FolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FolioKeyTyped
       char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
       
        Folio.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 2;
            public void keyTyped(KeyEvent e) {
                if (Folio.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
}//GEN-LAST:event_FolioKeyTyped

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        String Cadena = Nombre.getText();
        Nombre.setText(Cadena.toUpperCase());
}//GEN-LAST:event_NombreActionPerformed

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE)) evt.consume(); getToolkit().beep();
        Nombre.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 15;
            public void keyTyped(KeyEvent e) {
                if (Nombre.getText().length()== limite)
                    e.consume();
                    getToolkit().beep();
                   
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
}//GEN-LAST:event_NombreKeyTyped

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
        String Cadena = Direccion.getText();
        Direccion.setText(Cadena.toUpperCase());
}//GEN-LAST:event_DireccionActionPerformed

    private void DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyTyped
        char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE))  evt.consume(); getToolkit().beep();
        Direccion.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 20;
            public void keyTyped(KeyEvent e) {
                if (Direccion.getText().length()== limite)
                    e.consume();
                    getToolkit().beep();
                    
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
}//GEN-LAST:event_DireccionKeyTyped

    private void RFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFCActionPerformed
        String Cadena = RFC.getText();
        RFC.setText(Cadena.toUpperCase());
}//GEN-LAST:event_RFCActionPerformed

    private void RFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RFCKeyTyped
        char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE)&& (c<'0'||c>'9')) evt.consume(); getToolkit().beep();
        RFC.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 13;
            public void keyTyped(KeyEvent e) {
                if (RFC.getText().length()== limite)
                    e.consume();
                    getToolkit().beep();
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
}//GEN-LAST:event_RFCKeyTyped

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        String Cadena = Email.getText();
        Email.setText(Cadena.toUpperCase());
}//GEN-LAST:event_EmailActionPerformed

    private void EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailKeyTyped
        char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE)&& (c<'0'||c>'9')) getToolkit().beep();
        Email.addKeyListener(new KeyListener(){
            int limite  = 20;
            public void keyTyped(KeyEvent e) {
                if (Email.getText().length()== limite)
                    e.consume();
                    getToolkit().beep();
                    
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
}//GEN-LAST:event_EmailKeyTyped

    private void TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        Telefono.addKeyListener(new KeyListener(){
            int limite  = 10;
            public void keyTyped(KeyEvent e) {
                if (Telefono.getText().length()== limite)
                    e.consume();
                    getToolkit().beep();
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
}//GEN-LAST:event_TelefonoKeyTyped

    private void PromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PromocionActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_PromocionActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
       int S=Se.getSelectedIndex();
if(S==0){
            Sexo.setText("Masculino");
        }
if(S==1){
            Sexo.setText("Femenino");
        }
        
       int P=Promocion.getSelectedIndex();
if(P==0){
          Promo.setText("Con Promoción");
    }
if(P==1){
          Promo.setText("Sin Promoción");
    }

       int D=Descuentos.getSelectedIndex();
if(D==0){
          Des.setText("Descuento");
    }
if(D==1){
          Des.setText("Sin Descuento");
    }

int Pa=Pago.getSelectedIndex();
if(Pa==0){
          Pago1.setText("Tarjeta");
    }
if(Pa==1){
          Pago1.setText("Efectivo");
    }

    }//GEN-LAST:event_jLabel16MouseClicked

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadActionPerformed

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseEntered

    private void PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PagoActionPerformed

    private void EdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EdadKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        Edad.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 2;
            public void keyTyped(KeyEvent e) {
                if (Edad.getText().length()== limite){
                   getToolkit().beep();
                   e.consume();
                }
                }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_EdadKeyTyped

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        int res = JOptionPane.showConfirmDialog(this, "¿Esta Usted Seguro de Salir del Sistema Carpiteria Carso?",
                "Sistema Farmacia Alex", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "Gracias por usar el Sistema");
            new Salir().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        new Clientes().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        new Clientes().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jLabel17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseReleased

    private void FotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FotoMouseClicked
         JFileChooser se= new JFileChooser();
        se.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int estado = se.showOpenDialog(null);
        if(estado == JFileChooser.APPROVE_OPTION)
        {
            try {

                fis =  new FileInputStream(se.getSelectedFile());
                this.longitudBytes = (int)se.getSelectedFile().length();

                Image icono = ImageIO.read(se.getSelectedFile()).getScaledInstance(Foto.getWidth(), Foto.getHeight(), Image.SCALE_DEFAULT);
                Foto.setIcon(new ImageIcon(icono));
                Foto.updateUI();

            } catch (FileNotFoundException ex) {ex.printStackTrace();}
            catch (IOException ex){ex.printStackTrace();}
        }
    }//GEN-LAST:event_FotoMouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JLabel ConExi;
    private javax.swing.JLabel Des;
    private javax.swing.JComboBox Descuentos;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Edad;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel FalloEnlace;
    private javax.swing.JLabel Fecha;
    private javax.swing.JTextField Folio;
    private javax.swing.JLabel Foto;
    private javax.swing.JLabel His;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel ImagenG;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Ope;
    private javax.swing.JScrollPane Otro;
    private javax.swing.JComboBox Pago;
    private javax.swing.JLabel Pago1;
    private javax.swing.JLabel Promo;
    private javax.swing.JComboBox Promocion;
    private javax.swing.JTextField RFC;
    private javax.swing.JComboBox Se;
    private javax.swing.JLabel Sexo;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField Telefono;
    private javax.swing.JLabel TextoExi;
    private javax.swing.JLabel TextoFallo;
    private javax.swing.JLabel TextoG;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables

}
