
package carpinteriacarso;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Consultas extends javax.swing.JFrame {
    DefaultTableModel modelo;
public Connection conexion;
    public Statement sentencia;
    public ResultSet resultado;
    public String Nombre1,Registro;
    public Integer Contrasena,cont;
    /** Creates new form Consultas */
    public Consultas() {
        initComponents();
String Cabecera[]={"Folio","Nombre","Edad","Dirección","RFC","Email","Telefono"};
String Datos [][]={};
modelo=new DefaultTableModel(Datos,Cabecera);
Tabla.setModel(modelo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cons = new javax.swing.JComboBox();
        Folio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cons.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Clientes", "Productos", "Empleados", "Nota / Factura", "Pedidos" }));
        Cons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsActionPerformed(evt);
            }
        });

        Folio.setText("00");
        Folio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FolioActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cons, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Folio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Folio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsActionPerformed
      if(Cons.getSelectedIndex()==0){
          try  {
            Class.forName( "com.mysql.jdbc.Driver" );
        } catch( Exception eve ) {
            JOptionPane.showMessageDialog(null,"Error en el Enlace, Sistema ");

            return;
        }
        try{
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/cc","root", "123");
            sentencia=conexion.createStatement();
            int res = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
            new Clientes().setVisible(true);
        this.dispose();
        }
        if( res == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));
        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
            resultado=sentencia.executeQuery("SELECT * FROM clientes WHERE Id_Cliente =" + Folio.getText());
            if (resultado.next()){
//Object Datos[]={
//
//}
                sentencia.close();
            } else {
                JOptionPane.showMessageDialog(null,"No existe el Empleado ");
            }}}
        } catch(SQLException exp){
        JOptionPane.showMessageDialog(null,"Error en la Conexion, Sistema ");

        }
      }
      if(Cons.getSelectedIndex()==1){
         
      }
      if(Cons.getSelectedIndex()==2){

      }
      if(Cons.getSelectedIndex()==3){

      }
      if(Cons.getSelectedIndex()==4){

      }
    }//GEN-LAST:event_ConsActionPerformed

    private void FolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FolioActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Cons;
    private javax.swing.JTextField Folio;
    private javax.swing.JTable Tabla;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
