package carpinteriacarso;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Calendar;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author J.h
 */
public class NotaFactura extends javax.swing.JFrame {
public Connection conexion;
    public Statement sentencia;
    public ResultSet resultado;
    public String Nombre1,Registro,Operacion;
    public Integer Contrasena,cont;
    /** Creates new form Nota */
    public NotaFactura() {
        initComponents();
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        FalloEnlace.setVisible(false);
        TextoFallo.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
          NN.setOpaque(false);
          Nombre.setOpaque(false);
          Dire.setOpaque(false);
          Tel.setOpaque(false);
          Can.setOpaque(false);
          Des.setOpaque(false);
          PU.setOpaque(false);
           Can1.setOpaque(false);
          Des1.setOpaque(false);
          PU1.setOpaque(false);
           Can2.setOpaque(false);
          Des2.setOpaque(false);
          PU2.setOpaque(false);
           Can3.setOpaque(false);
          Des3.setOpaque(false);
          PU3.setOpaque(false);
           Can4.setOpaque(false);
          Des4.setOpaque(false);
          PU4.setOpaque(false);
          Impo.setOpaque(false);
          Sut.setOpaque(false);
          IVa.setOpaque(false);
          To.setOpaque(false);
         
         
        Toolkit t=Toolkit.getDefaultToolkit();
        setIconImage(t.getImage(getClass().getResource("/carpinteriacarso/imagenes/log.jpg")));

         setTitle("Nota / Factura");
         Calendar cal=Calendar.getInstance();
          String fecha=cal.get(cal.DATE)+"/"+cal.get(cal.MONTH)+"/"+cal.get(cal.YEAR);
          String hora=cal.get(cal.HOUR_OF_DAY)+":"+cal.get(cal.MINUTE)+":"+cal.get(cal.SECOND);
          this.Fecha1.setText(fecha);
          this.Fecha.setText(fecha);
          this.Hora.setText(hora);
//          JOptionPane.showMessageDialog(rootPane,"Acceso: "+fecha+ ".... A la Hora: "+hora);
//          JOptionPane.showMessageDialog(rootPane,"Datos Almacenados");
          String Nom = JOptionPane.showInputDialog(rootPane, "Introduce tu Nombre");
        Registro = String.valueOf(String.valueOf(Nom));
        Nombre2.setText(String.valueOf(Registro));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Lu = new javax.swing.JLabel();
        Lugar = new javax.swing.JComboBox();
        NN = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Tip = new javax.swing.JLabel();
        S = new javax.swing.JComboBox();
        Ci = new javax.swing.JComboBox();
        Ciu = new javax.swing.JLabel();
        Tel = new javax.swing.JTextField();
        Can = new javax.swing.JTextField();
        Des = new javax.swing.JTextField();
        PU = new javax.swing.JTextField();
        Impo = new javax.swing.JLabel();
        Sut = new javax.swing.JLabel();
        IVa = new javax.swing.JLabel();
        To = new javax.swing.JLabel();
        Can1 = new javax.swing.JTextField();
        Des1 = new javax.swing.JTextField();
        PU1 = new javax.swing.JTextField();
        Can2 = new javax.swing.JTextField();
        PU2 = new javax.swing.JTextField();
        Des2 = new javax.swing.JTextField();
        Can3 = new javax.swing.JTextField();
        PU3 = new javax.swing.JTextField();
        Des3 = new javax.swing.JTextField();
        Can4 = new javax.swing.JTextField();
        PU4 = new javax.swing.JTextField();
        Des4 = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        ImagenG = new javax.swing.JLabel();
        TextoG = new javax.swing.JLabel();
        FalloEnlace = new javax.swing.JLabel();
        TextoFallo = new javax.swing.JLabel();
        ConExi = new javax.swing.JLabel();
        TextoExi = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JLabel();
        Dire = new javax.swing.JTextField();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        Imagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        Ayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 0, 48));
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Nota");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 121, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Altas.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Bajas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 70, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Bajas.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Consultas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Consultas.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Guardar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Guardar.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Actualizar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Actualizar.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/go-back64.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 630, -1, -1));

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Altas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 70, 40));

        Fecha.setFont(new java.awt.Font("Viner Hand ITC", 0, 18));
        Fecha.setForeground(new java.awt.Color(240, 240, 240));
        Fecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 150, 60));

        Hora.setFont(new java.awt.Font("Viner Hand ITC", 0, 18));
        Hora.setForeground(new java.awt.Color(240, 240, 240));
        Hora.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora de Acceso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 140, 60));

        Nombre2.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        Nombre2.setForeground(new java.awt.Color(240, 240, 240));
        Nombre2.setText("Registro");
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 350, 40));

        jLabel18.setFont(new java.awt.Font("Viner Hand ITC", 0, 36));
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Bienvenido");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 200, 60));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/salir.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel17MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 630, -1, -1));

        Lu.setFont(new java.awt.Font("Arial", 0, 18));
        Lu.setForeground(new java.awt.Color(240, 240, 240));
        Lu.setText("Elige tu Municipio");
        Lu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lugar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(Lu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 510, 50));

        Lugar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige tu Municipio", "001  Acambay\tAcambay", "064  El Oro\tEl Oro de Hidalgo", "002  Acolman\tAcolman de Nezahualcóyotl", "065  Otumba \tOtumba de Gómez Farías", "003  Aculco\t     Aculco de Espinoza", "060  Otzoloapan\tOtzoloapan", "004  Almoloya de Alquisiras\tAlmoloya de Alquisiras", "067  Otzolotepec\tVilla Cuauhtémoc", "005  Almoloya de Juárez\tVilla de Almoloya de Juárez", "068  Ozumba\t              Ozumba de Alzate", "006  Almoloya del Río\tAlmoloya del Río", "069  Papalotla\tPapalotla", "007  Amanalco\tAmanalco", "070  La Paz\t       Los Reyes Acaquilpan", "008  Amatepec\tAmatepec", "071  Polotitlán\tPolotitlán de la Ilustración", "009  Amecameca\tAmecameca de Juárez", "072  Rayón\t      Santa María Rayón", "010  Apaxco\t        Apaxco de Ocampo", "073  San Antonio la Isla\tSan Antonio la Isla", "011  Atenco\t       San Salvador Atenco", "074  San Felipe del Progreso\tSan Felipe del Progreso", "012  Atizapán\tSanta Cruz Atizapán", "075  San Martín de las Pirámides\tSan Martín de las Pirámides", "013  Atizapán de Zaragoza\tCiudad López Mateos", "076  San Mateo Atenco\tSan Mateo Atenco", "014  Atlacomulco\tAtlacomulco de Favela", "077  San Simón de Guerrero\tSan Simón de Guerrero", "015  Atlautla\tAtlautla de Victoria", "078  Santo Tomás\tSanto Tomás de los Plátanos", "016  Axapusco\tAxapusco", "079  Soyaniquilpan de Juárez\tSan Francisco Soyaniquilpan", "017  Ayapango\tAyapango de Gabriel Ramos Millán", "080  Sultepec     Sultepec de Pedro Ascencio de Alquisiras", "018  Calimaya\tCalimaya de Díaz González", "081  Tecámac\tTecámac de Felipe Villanueva", "019  Capulhuac\tCapulhuac de Mirafuentes", "082  Tejupilco                     Tejupilco de Hidalgo", "020  Coacalco de Berriozábal\tSan Francisco Coacalco", "083  Temamatla\tTemamatla", "021  Coatepec Harinas\tCoatepec Harinas", "084  Temascalapa\tTemascalapa", "022  Cocotitlán\tCocotitlán", "085  Temascalcingo\tTemascalcingo de José María Velasco", "023  Coyotepec\tCoyotepec", "086  Temascaltepec\tTemascaltepec de González", "024  Cuautitlán\tCuautitlán", "087  Temoaya\tTemoaya", "025  Chalco\t            Chalco de Díaz Covarrubias", "088  Tenancingo\tTenancingo de Degollado", "026  Chapa de Mota\tChapa de Mota", "089  Tenango del Aire\tTenango del Aire", "027  Chapultepec\tChapultepec", "090  Tenango del Valle\tTenango de Arista", "028  Chiautla\tChiautla", "091  Teoloyucan\tTeoloyucan", "029  Chicoloapan\tChicoloapan", "092  Teotihuacán\tTeotihuacán de Arista", "030  Chiconcuac\tChiconcuac de Juárez", "093  Tepetlaoxtoc\tTepetlaoxtoc de Hidalgo", "031  Chimalhuacán\tChimalhuacán", "094  Tepetlixpa\tTepetlixpa", "032  Donato Guerra\t Villa Donato Guerra", "095  Tepotzotlán\t    Tepotzotlán", "033  Ecatepec de Morelos  \tEcatepec de Morelos", "096  Tequixquiac\tSantiago Tequixquiac", "034  Ecatzingo\tEcatzingo de Hidalgo", "097  Texcaltitlán\tTexcaltitlán", "035  Huehuetoca\tHuehuetoca", "098  Texcalyacac\tSan Mateo Texcalyacac", "036  Hueypoxtla\tHueypoxtla", "099  Texcoco\tTexcoco de Mora", "037  Huixquilucan\tHuixquilucan de Degollado", "100  Tezoyuca\tTezoyuca", "038  Isidro Fabela\tTlazala de Fabela", "101  Tianguistenco\tSantiago Tianguistenco de Galeana", "034  Ixtapaluca\tIxtapaluca", "102  Timilpan\tSan Andrés    Timilpan", "040  Ixtapan de la Sal\tIxtapan de la Sal", "103  Tlalmanalco\tTlalmanalco de Velázquez", "041  Ixtapan del Oro\tIxtapan del Oro", "104  Tlalnepantla de Baz\tTlalnepantla", "042  Ixtlahuaca\tIxtlahuaca de Rayón", "105  Tlatlaya\tTlatlaya", "043  Xalatlaco\tXalatlaco", "106  Toluca\t     Toluca de Lerdo", "044  Jaltenco\tJaltenco", "107  Tonatico\tTonatico", "045  Jilotepec\tJilotepec de Molina Enríquez", "108  Tultepec\tTultepec", "046  Jilotzingo\tSanta Ana Jilotzingo", "109  Tultitlán  \tTultilán de Mariano Escobedo", "047  Jiquipilco\tJiquipilco", "110  Valle de Bravo\tValle de Bravo", "048  Jocotitlán\tJocotitlán", "111  Villa de Allende\tSan José Villa de Allende", "049  Joquicingo\tJoquicingo de León Guzmán", "112  Villa del Carbón\tVilla del Carbón", "050  Juchitepec\tJuchitpec de Mariano Rivapalacio", "113  Villa Guerrero\tVilla Guerrero", "051  Lerma    \tLerma de Villada", "114  Villa Victoria\tVilla Victoria", "052  Malinalco\tMalinalco", "115  Xonacatlán\tXonacatlán", "053  Melchor Ocampo\tMelchor Ocampo", "116  Zacazonapan\tZacazonapan", "054  Metepec\tMetepec", "117  Zacualpan\tReal de Minas Zacualpan", "055  Mexicaltzingo\tSan Mateo Mexicaltzingo", "118  Zinacantepec\tSan Miguel Zinacantepec", "056  Morelos \tSan Bartolo Morelos", "119  Zumpahuacán\tZumpahuacán", "057  Naucalpan de Juárez\t      Naucalpan de Juárez", "120  Zumpango\tZumpango de Ocampo", "058  Nezahualcóyotl\tNezahualcóyotl", "121  Cuautitlán Izcalli\tCuautitlán Izcalli", "059  Nextlalpan\tSanta Ana Nextlalpan", "122  Valle de Chalco Solidaridad\tXico", "060  Nicolás Romero\tVilla Nicolás Romero", "123  Luvianos\tVilla Luvianos", "061  Nopaltepec\tNopaltepec", "124  San José del Rincón\tSan José del Rincón Centro", "062  Ocoyoacac\tOcoyoacac", "125  Tonanitla\tSanta Maria Tonanitla", "063  Ocuilan\t                     Ocuilan de Arteaga" }));
        Lugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugarActionPerformed(evt);
            }
        });
        getContentPane().add(Lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 170, 40));

        NN.setFont(new java.awt.Font("Arial", 0, 18));
        NN.setForeground(new java.awt.Color(240, 240, 240));
        NN.setText("000");
        NN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Numero de Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), new java.awt.Color(240, 240, 240))); // NOI18N
        NN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NNKeyTyped(evt);
            }
        });
        getContentPane().add(NN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 180, 50));

        Nombre.setFont(new java.awt.Font("Arial", 0, 14));
        Nombre.setForeground(new java.awt.Color(240, 240, 240));
        Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre Completo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 510, 50));

        Tip.setFont(new java.awt.Font("Arial", 0, 18));
        Tip.setForeground(new java.awt.Color(240, 240, 240));
        Tip.setText("Tipo");
        Tip.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Es", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(Tip, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 90, 50));

        S.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo", "Sr.", "Sra.", "Joven", "Lic.", "Ing." }));
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });
        getContentPane().add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 40));

        Ci.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elige tu Ciudad", "Acapulco", "Aguascalientes", "Ascensión", "Camargo", "Campeche", "Cancún", "Catemaco", "Chetumal", "Chihuahua", "Chilpancingo", "Ciudad Juárez", "Ciudad Victoria", "Coatzacoalcos", "Colima", "Creel", "Cuernavaca", "Culiacán", "Delicias", "Durango", "Guadalajara", "Guanajuato", "Hermosillo", "La Paz", "Los Mochis", "Madera", "Matamoros", "Mazatlán", "Mexicali", "Monclova", "Monterrey", "Morelia", "Mérida", "Nuevo Laredo", "Oaxaca", "Pachuca", "Parral", "Playa del Carmen", "Puebla", "Puerto Vallarta", "Querétaro", "Saltillo", "San Juanito", "San Luis Potosí", "San Miguel de Allende", "Sayulita", "Tampico", "Tepatitlan", "Tepic", "Tijuana", "Tlaxcala", "Toluca", "Tulancingo", "Tuxtla Gutiérrez", "Villa Ahumada", "Villahermosa", "Xalapa", "Zacatecas", "Zicatela", "Zipolite" }));
        Ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiActionPerformed(evt);
            }
        });
        getContentPane().add(Ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 120, 40));

        Ciu.setFont(new java.awt.Font("Arial", 0, 18));
        Ciu.setForeground(new java.awt.Color(240, 240, 240));
        Ciu.setText("Elige tu Ciudad");
        Ciu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ciudad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(Ciu, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 280, 50));

        Tel.setFont(new java.awt.Font("Arial", 0, 14));
        Tel.setForeground(new java.awt.Color(240, 240, 240));
        Tel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelActionPerformed(evt);
            }
        });
        Tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelKeyTyped(evt);
            }
        });
        getContentPane().add(Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 300, -1));

        Can.setFont(new java.awt.Font("Arial", 0, 18));
        Can.setForeground(new java.awt.Color(240, 240, 240));
        Can.setText("0");
        Can.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanActionPerformed(evt);
            }
        });
        Can.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CanKeyTyped(evt);
            }
        });
        getContentPane().add(Can, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 150, 40));

        Des.setFont(new java.awt.Font("Arial", 0, 18));
        Des.setForeground(new java.awt.Color(240, 240, 240));
        Des.setText("Articulo");
        Des.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesActionPerformed(evt);
            }
        });
        Des.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DesKeyTyped(evt);
            }
        });
        getContentPane().add(Des, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 360, 40));

        PU.setFont(new java.awt.Font("Arial", 0, 18));
        PU.setForeground(new java.awt.Color(240, 240, 240));
        PU.setText("0");
        PU.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio Unitario ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        PU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PUActionPerformed(evt);
            }
        });
        PU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PUKeyTyped(evt);
            }
        });
        getContentPane().add(PU, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 160, 40));

        Impo.setFont(new java.awt.Font("Arial", 0, 18));
        Impo.setForeground(new java.awt.Color(240, 240, 240));
        Impo.setText("00.00");
        Impo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Importe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(Impo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 120, 50));

        Sut.setFont(new java.awt.Font("Arial", 0, 18));
        Sut.setForeground(new java.awt.Color(240, 240, 240));
        Sut.setText("00.00");
        Sut.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sub Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(Sut, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 110, 50));

        IVa.setFont(new java.awt.Font("Arial", 0, 18));
        IVa.setForeground(new java.awt.Color(240, 240, 240));
        IVa.setText("00.00");
        IVa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IVA 16%", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(IVa, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, 110, 50));

        To.setFont(new java.awt.Font("Arial", 0, 18));
        To.setForeground(new java.awt.Color(240, 240, 240));
        To.setText("00.00");
        To.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, 110, 50));

        Can1.setFont(new java.awt.Font("Arial", 0, 18));
        Can1.setForeground(new java.awt.Color(240, 240, 240));
        Can1.setText("0");
        Can1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Can1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Can1ActionPerformed(evt);
            }
        });
        Can1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Can1KeyTyped(evt);
            }
        });
        getContentPane().add(Can1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 150, 40));

        Des1.setFont(new java.awt.Font("Arial", 0, 18));
        Des1.setForeground(new java.awt.Color(240, 240, 240));
        Des1.setText("Articulo");
        Des1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Des1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Des1ActionPerformed(evt);
            }
        });
        Des1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Des1KeyTyped(evt);
            }
        });
        getContentPane().add(Des1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 360, 40));

        PU1.setFont(new java.awt.Font("Arial", 0, 18));
        PU1.setForeground(new java.awt.Color(240, 240, 240));
        PU1.setText("0");
        PU1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio Unitario ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        PU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PU1ActionPerformed(evt);
            }
        });
        PU1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PU1KeyTyped(evt);
            }
        });
        getContentPane().add(PU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 160, 40));

        Can2.setFont(new java.awt.Font("Arial", 0, 18));
        Can2.setForeground(new java.awt.Color(240, 240, 240));
        Can2.setText("0");
        Can2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Can2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Can2ActionPerformed(evt);
            }
        });
        Can2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Can2KeyTyped(evt);
            }
        });
        getContentPane().add(Can2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 150, 40));

        PU2.setFont(new java.awt.Font("Arial", 0, 18));
        PU2.setForeground(new java.awt.Color(240, 240, 240));
        PU2.setText("0");
        PU2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio Unitario ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        PU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PU2ActionPerformed(evt);
            }
        });
        PU2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PU2KeyTyped(evt);
            }
        });
        getContentPane().add(PU2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 160, 40));

        Des2.setFont(new java.awt.Font("Arial", 0, 18));
        Des2.setForeground(new java.awt.Color(240, 240, 240));
        Des2.setText("Articulo");
        Des2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Des2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Des2ActionPerformed(evt);
            }
        });
        Des2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Des2KeyTyped(evt);
            }
        });
        getContentPane().add(Des2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 360, 40));

        Can3.setFont(new java.awt.Font("Arial", 0, 18));
        Can3.setForeground(new java.awt.Color(240, 240, 240));
        Can3.setText("0");
        Can3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Can3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Can3ActionPerformed(evt);
            }
        });
        Can3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Can3KeyTyped(evt);
            }
        });
        getContentPane().add(Can3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 150, 40));

        PU3.setFont(new java.awt.Font("Arial", 0, 18));
        PU3.setForeground(new java.awt.Color(240, 240, 240));
        PU3.setText("0");
        PU3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio Unitario ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        PU3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PU3ActionPerformed(evt);
            }
        });
        PU3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PU3KeyTyped(evt);
            }
        });
        getContentPane().add(PU3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 160, 40));

        Des3.setFont(new java.awt.Font("Arial", 0, 18));
        Des3.setForeground(new java.awt.Color(240, 240, 240));
        Des3.setText("Articulo");
        Des3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Des3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Des3ActionPerformed(evt);
            }
        });
        Des3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Des3KeyTyped(evt);
            }
        });
        getContentPane().add(Des3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 360, 40));

        Can4.setFont(new java.awt.Font("Arial", 0, 18));
        Can4.setForeground(new java.awt.Color(240, 240, 240));
        Can4.setText("0");
        Can4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Can4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Can4ActionPerformed(evt);
            }
        });
        Can4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Can4KeyTyped(evt);
            }
        });
        getContentPane().add(Can4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 150, 40));

        PU4.setFont(new java.awt.Font("Arial", 0, 18));
        PU4.setForeground(new java.awt.Color(240, 240, 240));
        PU4.setText("0");
        PU4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio Unitario ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        PU4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PU4ActionPerformed(evt);
            }
        });
        PU4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PU4KeyTyped(evt);
            }
        });
        getContentPane().add(PU4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, 160, 40));

        Des4.setFont(new java.awt.Font("Arial", 0, 18));
        Des4.setForeground(new java.awt.Color(240, 240, 240));
        Des4.setText("Articulo");
        Des4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Des4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Des4ActionPerformed(evt);
            }
        });
        Des4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Des4KeyTyped(evt);
            }
        });
        getContentPane().add(Des4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 360, 40));

        Calcular.setFont(new java.awt.Font("Arial", 0, 14));
        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        getContentPane().add(Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 100, -1));

        ImagenG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/AgregadoExi.png"))); // NOI18N
        getContentPane().add(ImagenG, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 140, -1));

        TextoG.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        TextoG.setForeground(new java.awt.Color(240, 240, 240));
        TextoG.setText("Dato Agregado Exitosamente");
        getContentPane().add(TextoG, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 580, -1, -1));

        FalloEnlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Fallo Enlace.png"))); // NOI18N
        getContentPane().add(FalloEnlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 140, -1));

        TextoFallo.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        TextoFallo.setForeground(new java.awt.Color(240, 240, 240));
        TextoFallo.setText("Error de enlace con la Base de Datos");
        getContentPane().add(TextoFallo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, 400, 30));

        ConExi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/ConsultaExitosa.png"))); // NOI18N
        getContentPane().add(ConExi, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, -1, -1));

        TextoExi.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        TextoExi.setForeground(new java.awt.Color(240, 240, 240));
        TextoExi.setText("Consulta Exitosa");
        getContentPane().add(TextoExi, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 580, 200, 40));

        Fecha1.setFont(new java.awt.Font("Viner Hand ITC", 0, 18));
        Fecha1.setForeground(new java.awt.Color(240, 240, 240));
        Fecha1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de Acceso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 150, 60));

        Dire.setFont(new java.awt.Font("Arial", 0, 14));
        Dire.setForeground(new java.awt.Color(240, 240, 240));
        Dire.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Dire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireActionPerformed(evt);
            }
        });
        getContentPane().add(Dire, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 400, 50));
        getContentPane().add(dateChooserCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        Imagen.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Imagen.setForeground(new java.awt.Color(240, 240, 240));
        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Fon5T.jpg"))); // NOI18N
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu3.setText("Archivo");

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Nuevo");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Actualizar");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu3);

        Ayuda.setText("Ayuda");
        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
         // Altas
        //Folio.disable();//DESHABILITAR LA CAJA DE TEXTO DE BUSCAR

        int res = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
            new Clientes().setVisible(true);
        this.dispose();
        }
        if( res == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));
        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
        NN.setText("");
        //HABILITAR TODOS LOS TEXTFIELDS PARA EL INGRESO DE DATOS
        Lu.enable(true);
        //Fecha1.enable(true);
        Nombre.enable(true);
        Tip.enable(true);
        Dire.enable(true);
        Ciu.enable(true);
        Tel.enable(true);
        Can.enable(true);
        Des.enable(true);
        PU.enable(true);
        Can1.enable(true);
        Des1.enable(true);
        PU1.enable(true);
        Can2.enable(true);
        Des2.enable(true);
        PU2.enable(true);
        Can3.enable(true);
        Des3.enable(true);
        PU3.enable(true);
        Can4.enable(true);
        Des4.enable(true);
        PU4.enable(true);
        Impo.enable(true);
        Sut.enable(true);
        IVa.enable(true);
        To.enable(true);

        //Se limpia cajas de texto
        Lu.setText("");
        Nombre.setText("");
        Tip.setText("");
        Dire.setText("");
        Ciu.setText("");
        Tel.setText("");
        Can.setText("");
        Des.setText("");
        PU.setText("");
        Can1.setText("");
        Des1.setText("");
        PU1.setText("");
        Can2.setText("");
        Des2.setText("");
        PU2.setText("");
        Can3.setText("");
        Des3.setText("");
        PU3.setText("");
        Can4.setText("");
        Des4.setText("");
        PU4.setText("");
        Impo.setText("");
        Sut.setText("");
        IVa.setText("");
        To.setText("");
        }}
}//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        try {
            Class.forName(  "com.mysql.jdbc.Driver" );
        } catch( Exception eve ) {
            JOptionPane.showMessageDialog(null,"Fallo Enlace, Sistema ");
            FalloEnlace.setVisible(true);
            TextoFallo.setVisible(true);
            ImagenG.setVisible(false);
        TextoG.setVisible(false);
        FalloEnlace.setVisible(false);
        ConExi.setVisible(false);
            return;
        }
        try{
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/cc","root", "123");
            sentencia=conexion.createStatement();
            int res1 = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res1 == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
            new Clientes().setVisible(true);
        this.dispose();
        }
        if( res1 == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));
        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
            sentencia.execute("DELETE FROM nota WHERE Id_Nota = "+NN.getText());
            int res = JOptionPane.showConfirmDialog( this,"¿Esta Usted Seguro de dar de Baja",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(null,"Baja Cancelada...!!!");
            sentencia.close();
        }
           if( res == JOptionPane.YES_OPTION ) {
        Lu.setText("");
        Nombre.setText("");
        Tip.setText("");
        Dire.setText("");
        Ciu.setText("");
        Tel.setText("");
        Can.setText("");
        Des.setText("");
        PU.setText("");
        Can1.setText("");
        Des1.setText("");
        PU1.setText("");
        Can2.setText("");
        Des2.setText("");
        PU2.setText("");
        Can3.setText("");
        Des3.setText("");
        PU3.setText("");
        Can4.setText("");
        Des4.setText("");
        PU4.setText("");
        Impo.setText("");
        Sut.setText("");
        IVa.setText("");
        To.setText("");
            }}}
        } catch(SQLException x){JOptionPane.showMessageDialog(null,"Fallo Enlace, Sistema  ");
        FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
        }
}//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // Consultar

        try  {
            Class.forName( "com.mysql.jdbc.Driver" );
        } catch( Exception eve ) {
            JOptionPane.showMessageDialog(null,"Error en el Enlace, Sistema ");
            FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoFallo.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
            return;
        }
        try{
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/cc","root", "123");
            sentencia=conexion.createStatement();
            int res = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
            new Clientes().setVisible(true);
        this.dispose();
        }
        if( res == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));
        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
            resultado=sentencia.executeQuery("SELECT * FROM nota WHERE Id_Nota=" + NN.getText());
            if (resultado.next()){
                Lu.setText(String.valueOf(resultado.getString(2)));
                Fecha.setText(String.valueOf(resultado.getString(3)));
                Nombre.setText(String.valueOf(resultado.getString(4)));
                Tip.setText(String.valueOf(resultado.getString(5)));
                Dire.setText(String.valueOf(resultado.getString(6)));
                Ciu.setText(String.valueOf(resultado.getString(7)));
                Tel.setText(String.valueOf(resultado.getString(8)));
                Can.setText(String.valueOf(resultado.getString(9)));
                Des.setText(String.valueOf(resultado.getString(10)));
                PU.setText(String.valueOf(resultado.getString(11)));
                Can1.setText(String.valueOf(resultado.getString(12)));
                Des1.setText(String.valueOf(resultado.getString(13)));
                PU1.setText(String.valueOf(resultado.getString(14)));
                Can2.setText(String.valueOf(resultado.getString(15)));
                Des2.setText(String.valueOf(resultado.getString(16)));
                PU2.setText(String.valueOf(resultado.getString(17)));
                Can3.setText(String.valueOf(resultado.getString(18)));
                Des3.setText(String.valueOf(resultado.getString(19)));
                PU3.setText(String.valueOf(resultado.getString(20)));
                Can4.setText(String.valueOf(resultado.getString(21)));
                Des4.setText(String.valueOf(resultado.getString(22)));
                PU4.setText(String.valueOf(resultado.getString(23)));
                Impo.setText(String.valueOf(resultado.getString(24)));
                Sut.setText(String.valueOf(resultado.getString(25)));
                IVa.setText(String.valueOf(resultado.getString(26)));
                To.setText(String.valueOf(resultado.getString(27)));
//                Folio.setText("");
//                Nombre.setText("");
//            Edad.setText("");
//            Direccion.setText("");
//            RFC.setText("");
//            Email.setText("");
//            Telefono.setText("");
//            Promo.setText("");
//            Des.setText("");
//            Pago1.setText("");
//            Sexo.setText("");
                TextoExi.setVisible(true);
                ConExi.setVisible(true);
                ImagenG.setVisible(false);
                TextoG.setVisible(false);
                FalloEnlace.setVisible(false);
                TextoFallo.setVisible(false);
                sentencia.close();
            } else {
                JOptionPane.showMessageDialog(null,"No existe la Nota ");
            }}}
        } catch(SQLException exp){
        JOptionPane.showMessageDialog(null,"Error en la Conexion, Sistema ");
        FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
        }
}//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
       // Guardar
if(NN.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo Numero de Venta esta vacio");
 }
if(Lu.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo Lugar está vacío ");
 }
if(Fecha.getText().trim().length()==0)
 {
 JOptionPane.showMessageDialog(this, "El campo de Fecha está vacío ");
 }
if(Nombre.getText().trim().length()==0)
 {
 JOptionPane.showMessageDialog(this, "El campo de Nombre está vacío ");
 }
if(Dire.getText().trim().length()==0)
 {
 JOptionPane.showMessageDialog(this, "El campo de Dirección está vacío ");
 }
if(Ciu.getText().trim().length()==0)
 {
 JOptionPane.showMessageDialog(this, "El campo de Ciudad está vacío ");
 }
if(Tel.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Telefono está vacío ");
 }
if(Can.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Cantidad está vacío ");
 }
if(Des.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Descripción está vacío ");
 }
if(PU.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Precio Unitario está vacío ");
 }

        try {
            Class.forName(  "com.mysql.jdbc.Driver" );
        } catch( Exception eve ) {
            JOptionPane.showMessageDialog(null,"Fallo Enlace del Puente, Sistema"+eve);
            FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
            return;
        }
        if(Lu.getText()=="") {
            Lu.setText("");
        }
        if(Fecha.getText()=="") {
            Fecha.setText("");
        }
      if(Nombre.getText()=="") {
            Nombre.setText("");
        }
        if(Tip.getText()=="") {
            Tip.setText("");
        }
        if(Dire.getText()=="") {
            Dire.setText("");
        }
        if(Ciu.getText()=="") {
            Ciu.setText("");
        }
        if(Tel.getText()=="") {
            Tel.setText("");
        }
        if(Can.getText()=="") {
            Can.setText("");
        }
        if(Des.getText()=="") {
            Des.setText("");
        }
        if(PU.getText()=="") {
            PU.setText("");
        }
        if(Can1.getText()=="") {
            Can1.setText("");
        }
        if(Des1.getText()=="") {
            Des1.setText("");
        }
        if(PU1.getText()=="") {
            PU1.setText("");
        }
        if(Can2.getText()=="") {
            Can2.setText("");
        }
        if(Des2.getText()=="") {
            Des2.setText("");
        }
        if(PU2.getText()=="") {
            PU2.setText("");
        }
        if(Can3.getText()=="") {
            Can3.setText("");
        }
        if(Des3.getText()=="") {
            Des3.setText("");
        }
        if(PU3.getText()=="") {
            PU3.setText("");
        }
        if(Can4.getText()=="") {
            Can4.setText("");
        }
        if(Des4.getText()=="") {
            Des4.setText("");
        }
        if(PU4.getText()=="") {
            PU4.setText("");
        }

        try{
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/cc","root", "123");
            sentencia=conexion.createStatement();
            sentencia.executeUpdate("INSERT INTO nota"+
                    " VALUES ('"+NN.getText()+"',"+
                    "'"+Lu.getText()+"',"+
                    "'"+Fecha.getText()+"',"+
                    "'"+Nombre.getText()+"',"+
                    "'"+Tip.getText()+"',"+
                    "'"+Dire.getText()+"',"+
                    "'"+Ciu.getText()+"',"+
                    "'"+Tel.getText()+"',"+
                    "'"+Can.getText()+"',"+
                    "'"+Des.getText()+"',"+
                    "'"+PU.getText()+"',"+
                    "'"+Can1.getText()+"',"+
                    "'"+Des1.getText()+"',"+
                    "'"+PU1.getText()+"',"+
                    "'"+Can2.getText()+"',"+
                    "'"+Des2.getText()+"',"+
                    "'"+PU2.getText()+"',"+
                    "'"+Can3.getText()+"',"+
                    "'"+Des3.getText()+"',"+
                    "'"+PU3.getText()+"',"+
                    "'"+Can4.getText()+"',"+
                    "'"+Des4.getText()+"',"+
                    "'"+PU4.getText()+"',"+
                    "'"+Impo.getText()+"',"+
                    "'"+Sut.getText()+"',"+
                    "'"+IVa.getText()+"',"+
                    "'"+To.getText()+"')");

        NN.setText("");
        Lu.setText("");
        Nombre.setText("");
        Tip.setText("");
        Dire.setText("");
        Ciu.setText("");
        Tel.setText("");
        Can.setText("");
        Des.setText("");
        PU.setText("");
        Can1.setText("");
        Des1.setText("");
        PU1.setText("");
        Can2.setText("");
        Des2.setText("");
        PU2.setText("");
        Can3.setText("");
        Des3.setText("");
        PU3.setText("");
        Can4.setText("");
        Des4.setText("");
        PU4.setText("");
        Impo.setText("");
        Sut.setText("");
        IVa.setText("");
        To.setText("");

            conexion.close();
            JOptionPane.showMessageDialog(null,"Nota Guardado ");
            ImagenG.setVisible(true);
        TextoG.setVisible(true);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
         FalloEnlace.setVisible(false);
        TextoFallo.setVisible(false);
        } catch(SQLException p){ JOptionPane.showMessageDialog(null,"Error en el enlace, Sistema"+p);
        FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);}

//        //LIMPIAR CAJA DE TEXTO UNA VEZ GUARDADA LA INFORMACION.
//         Folio.setText("");
//         Nombre.setText("");
//         IniciodeOperacion.setText("");
//         Edad.setText("");
//         Sexo.setText("");
//         Puesto.setText("");
//         Salario.setText("");
//         CP.setText("");
//         Calle.setText("");
//         Colonia.setText("");
//         Mz.setText("");
//         Lt.setText("");
//         TP.setText("");
//         TC.setText("");
//         TR.setText("");
//         Email.setText("");
//         curp.setText("");
//        //HABILITAR LA CAJA DE TEXTO DE BUSCAR.
        NN.enable();
}//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
         try  {
            Class.forName( "com.mysql.jdbc.Driver" );
        } catch( Exception eve ) {
            JOptionPane.showMessageDialog(null,"Error en el Enlace, Sistema ");
            FalloEnlace.setVisible(true);
            TextoFallo.setVisible(true);
            ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
            return;
        }
        try{
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/cc","root", "123");
            sentencia=conexion.createStatement();
             int res = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
            new Clientes().setVisible(true);
        this.dispose();
        }
        if( res == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));
        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
            sentencia.execute("UPDATE nota SET "
                    + "Lugar=("+Lu.getText()+"),"
                    + "Fecha=("+Fecha.getText()+"),"
                    + "Nombre=('"+Nombre.getText()+"'),"
                    + "Tipo=("+Tip.getText()+"),"
                    + "Direccion=('"+Dire.getText()+"'),"
                    + "Ciudad=("+Ciu.getText()+"),"
                    + "Telefono=('"+Tel.getText()+"'),"
                    + "Cantidad=('"+Can.getText()+"'),"
                    + "Descripcion=('"+Des.getText()+"'),"
                    + "PU=('"+PU.getText()+"'),"
                    + "Cantidad1=('"+Can1.getText()+"'),"
                    + "Descripcion1=('"+Des1.getText()+"'),"
                    + "PU1=('"+PU1.getText()+"'),"
                    + "Cantidad2=('"+Can2.getText()+"'),"
                    + "Descripcion2=('"+Des2.getText()+"'),"
                    + "PU2=('"+PU2.getText()+"'),"
                    + "Cantidad3=('"+Can3.getText()+"'),"
                    + "Descripcion3=('"+Des3.getText()+"'),"
                    + "PU3=('"+PU3.getText()+"'),"
                    + "Cantidad4=('"+Can4.getText()+"'),"
                    + "Descripcion4=('"+Des4.getText()+"'),"
                    + "PU4=('"+PU4.getText()+"'),"
                    + "Importe=('"+Impo.getText()+"'),"
                    + "sudtotal=('"+Sut.getText()+"'),"
                    + "Iva=('"+IVa.getText()+"'),"
                    + "Total=('"+To.getText()+"')"
                    + " WHERE Id_Nota=" + NN.getText());
            JOptionPane.showMessageDialog(null,"Cambios Realizados, Nota Guardado ");
        }}
            sentencia.close();
        } catch (SQLException e2){
            JOptionPane.showMessageDialog(null,"Fallo Enlace, Sistema "+e2);
         FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
        }
}//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        new Menu().setVisible(true);
        this.dispose();
}//GEN-LAST:event_jLabel15MouseClicked

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        new NotaFactura().setVisible(true);
        this.dispose();
}//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        new NotaFactura().setVisible(true);
        this.dispose();
}//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        int res = JOptionPane.showConfirmDialog(this, "¿Esta Usted Seguro de Salir del Sistema Carpiteria Carso?",
                "Sistema Farmacia Alex", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "Gracias por usar el Sistema");
            new Salir().setVisible(true);
            this.dispose();
        }
}//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseReleased
        // TODO add your handling code here:
}//GEN-LAST:event_jLabel17MouseReleased

    private void LugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugarActionPerformed
        Lu.setText(Lugar.getSelectedItem().toString());
    }//GEN-LAST:event_LugarActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
       Tip.setText(S.getSelectedItem().toString());
    }//GEN-LAST:event_SActionPerformed

    private void CiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiActionPerformed
       Ciu.setText(Ci.getSelectedItem().toString());
    }//GEN-LAST:event_CiActionPerformed

    private void TelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelActionPerformed

    private void CanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanActionPerformed
          
    }//GEN-LAST:event_CanActionPerformed

    private void PUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PUActionPerformed
       
    }//GEN-LAST:event_PUActionPerformed

    private void Can1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Can1ActionPerformed
      
    }//GEN-LAST:event_Can1ActionPerformed

    private void PU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PU1ActionPerformed
       
    }//GEN-LAST:event_PU1ActionPerformed

    private void Can2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Can2ActionPerformed
       
    }//GEN-LAST:event_Can2ActionPerformed

    private void PU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PU2ActionPerformed
      
    }//GEN-LAST:event_PU2ActionPerformed

    private void Can3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Can3ActionPerformed
      
    }//GEN-LAST:event_Can3ActionPerformed

    private void PU3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PU3ActionPerformed
     
    }//GEN-LAST:event_PU3ActionPerformed

    private void Can4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Can4ActionPerformed
      
    }//GEN-LAST:event_Can4ActionPerformed

    private void PU4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PU4ActionPerformed
       
    }//GEN-LAST:event_PU4ActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
          int Ca=Integer.parseInt(Can.getText());
          int PE=Integer.parseInt(PU.getText());
          int Suma0=(PE*Ca);

          int Ca1=Integer.parseInt(Can1.getText());
          int PE1=Integer.parseInt(PU1.getText());
          int Suma1=(PE1*Ca1)+Suma0;

          int Ca2=Integer.parseInt(Can2.getText());
          int PE2=Integer.parseInt(PU2.getText());
          int Suma2=(PE2*Ca2)+Suma1;

          int Ca3=Integer.parseInt(Can3.getText());
          int PE3=Integer.parseInt(PU3.getText());
          int Suma3=(PE3*Ca3)+Suma2;

          int Ca4=Integer.parseInt(Can4.getText());
          int PE4=Integer.parseInt(PU4.getText());
          int Suma4=(PE4*Ca4)+Suma3;

          int SumaT=Suma4;
          Impo.setText(String.valueOf(SumaT));
          Sut.setText(String.valueOf(SumaT));
          Double Iva=SumaT*0.16;
          Double Tot=SumaT+Iva;
          IVa.setText(String.valueOf(Iva));
          To.setText(String.valueOf(Tot));

    }//GEN-LAST:event_CalcularActionPerformed

    private void DesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DesKeyTyped
       char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE)) evt.consume(); getToolkit().beep();
Des.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 25;
            public void keyTyped(KeyEvent e) {
                if (Des.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_DesKeyTyped

    private void Des1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Des1KeyTyped
       char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE)) evt.consume(); getToolkit().beep();
Des1.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 25;
            public void keyTyped(KeyEvent e) {
                if (Des1.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_Des1KeyTyped

    private void Des2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Des2KeyTyped
        char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE)) evt.consume(); getToolkit().beep();
Des2.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 25;
            public void keyTyped(KeyEvent e) {
                if (Des2.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_Des2KeyTyped

    private void Des3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Des3KeyTyped
        char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE)) evt.consume(); getToolkit().beep();
Des3.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 25;
            public void keyTyped(KeyEvent e) {
                if (Des3.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_Des3KeyTyped

    private void Des4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Des4KeyTyped
        char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE)) evt.consume(); getToolkit().beep();
Des4.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 25;
            public void keyTyped(KeyEvent e) {
                if (Des4.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_Des4KeyTyped

    private void TelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        Tel.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 10;
            public void keyTyped(KeyEvent e) {
                if (Tel.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_TelKeyTyped

    private void CanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CanKeyTyped
       char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
       Can.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 3;
            public void keyTyped(KeyEvent e) {
                if (Can.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_CanKeyTyped

    private void Can1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Can1KeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        Can1.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 15;
            public void keyTyped(KeyEvent e) {
                if (Can1.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_Can1KeyTyped

    private void Can2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Can2KeyTyped
       char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        Can2.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 15;
            public void keyTyped(KeyEvent e) {
                if (Can2.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_Can2KeyTyped

    private void Can3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Can3KeyTyped
      char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
       Can3.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 15;
            public void keyTyped(KeyEvent e) {
                if (Can3.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_Can3KeyTyped

    private void Can4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Can4KeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        Can4.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 15;
            public void keyTyped(KeyEvent e) {
                if (Can4.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_Can4KeyTyped

    private void PUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PUKeyTyped
       char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        PU.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 10;
            public void keyTyped(KeyEvent e) {
                if (PU.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_PUKeyTyped

    private void PU1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PU1KeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
         PU1.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 10;
            public void keyTyped(KeyEvent e) {
                if (PU1.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_PU1KeyTyped

    private void PU2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PU2KeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
         PU2.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 10;
            public void keyTyped(KeyEvent e) {
                if (PU2.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_PU2KeyTyped

    private void PU3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PU3KeyTyped
       char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        PU3.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 10;
            public void keyTyped(KeyEvent e) {
                if (PU3.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_PU3KeyTyped

    private void PU4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PU4KeyTyped
       char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        PU4.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 10;
            public void keyTyped(KeyEvent e) {
                if (PU4.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_PU4KeyTyped

    private void NNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NNKeyTyped
char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
 NN.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 5;
            public void keyTyped(KeyEvent e) {
                if (NN.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_NNKeyTyped

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
      String Cadena = Nombre.getText();
        Nombre.setText(Cadena.toUpperCase());
    }//GEN-LAST:event_NombreActionPerformed

    private void DireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireActionPerformed
      String Cadena = Dire.getText();
        Dire.setText(Cadena.toUpperCase());
    }//GEN-LAST:event_DireActionPerformed

    private void DesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesActionPerformed
       String Cadena = Des.getText();
        Des.setText(Cadena.toUpperCase());
    }//GEN-LAST:event_DesActionPerformed

    private void Des1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Des1ActionPerformed
        String Cadena = Des1.getText();
        Des1.setText(Cadena.toUpperCase());
    }//GEN-LAST:event_Des1ActionPerformed

    private void Des2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Des2ActionPerformed
        String Cadena = Des2.getText();
        Des2.setText(Cadena.toUpperCase());
    }//GEN-LAST:event_Des2ActionPerformed

    private void Des3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Des3ActionPerformed
       String Cadena = Des3.getText();
        Des3.setText(Cadena.toUpperCase());
    }//GEN-LAST:event_Des3ActionPerformed

    private void Des4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Des4ActionPerformed
        String Cadena = Des4.getText();
        Des4.setText(Cadena.toUpperCase());
    }//GEN-LAST:event_Des4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField Can;
    private javax.swing.JTextField Can1;
    private javax.swing.JTextField Can2;
    private javax.swing.JTextField Can3;
    private javax.swing.JTextField Can4;
    private javax.swing.JComboBox Ci;
    private javax.swing.JLabel Ciu;
    private javax.swing.JLabel ConExi;
    private javax.swing.JTextField Des;
    private javax.swing.JTextField Des1;
    private javax.swing.JTextField Des2;
    private javax.swing.JTextField Des3;
    private javax.swing.JTextField Des4;
    private javax.swing.JTextField Dire;
    private javax.swing.JLabel FalloEnlace;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Fecha1;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel IVa;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel ImagenG;
    private javax.swing.JLabel Impo;
    private javax.swing.JLabel Lu;
    private javax.swing.JComboBox Lugar;
    private javax.swing.JTextField NN;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JTextField PU;
    private javax.swing.JTextField PU1;
    private javax.swing.JTextField PU2;
    private javax.swing.JTextField PU3;
    private javax.swing.JTextField PU4;
    private javax.swing.JComboBox S;
    private javax.swing.JLabel Sut;
    private javax.swing.JTextField Tel;
    private javax.swing.JLabel TextoExi;
    private javax.swing.JLabel TextoFallo;
    private javax.swing.JLabel TextoG;
    private javax.swing.JLabel Tip;
    private javax.swing.JLabel To;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
