package carpinteriacarso;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Calendar;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author J.h
 */
public class Pedidos extends javax.swing.JFrame {

    DefaultTableModel modelo;
    public Connection conexion;
    public Statement sentencia;
    public ResultSet resultado;
    public String Nombre1,Registro,Operacion;
    public Integer Contrasena,cont;
    public FileInputStream fis;
    public int longitudBytes;



    /** Creates new form Pedidos */
    public Pedidos() {
        initComponents();
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        FalloEnlace.setVisible(false);
        TextoFallo.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
          NP.setOpaque(false);
          NC.setOpaque(false);
          NoP.setOpaque(false);
          Tel.setOpaque(false);
          Direccion.setOpaque(false);
          CodigoP.setOpaque(false);
          Email.setOpaque(false);
          FP.setOpaque(false);
          FE.setOpaque(false);
          EnvioL.setOpaque(false);
          CanL.setOpaque(false);
          IVA.setOpaque(false);
          Costo.setOpaque(false);
          CostoE.setOpaque(false);
          Producto.setOpaque(false);
          To.setOpaque(false);
            Otro.setVisible(false);

          Toolkit t=Toolkit.getDefaultToolkit();
        setIconImage(t.getImage(getClass().getResource("/carpinteriacarso/imagenes/log.jpg")));

         setTitle("Nota / Factura");
         Calendar cal=Calendar.getInstance();
          String fecha=cal.get(cal.DATE)+"/"+cal.get(cal.MONTH)+"/"+cal.get(cal.YEAR);
          String hora=cal.get(cal.HOUR_OF_DAY)+":"+cal.get(cal.MINUTE)+":"+cal.get(cal.SECOND);
          this.Fecha1.setText(fecha);
          this.FA.setText(fecha);
          this.Hora.setText(hora);
//          JOptionPane.showMessageDialog(rootPane,"Acceso: "+fecha+ ".... A la Hora: "+hora);
//          JOptionPane.showMessageDialog(rootPane,"Datos Almacenados");
          String Nom = JOptionPane.showInputDialog(rootPane, "Introduce tu Nombre");
        Registro = String.valueOf(String.valueOf(Nom));
        Nombre2.setText(String.valueOf(Registro));

        Otro.setOpaque(false);
        Tabla.setOpaque(false);
        String Cabecera[]={"Consultor","Fecha","Hora","Operacion","Num.Pedido","Nom.Cliente","Nom.Pedido","Dirección","Total","Fecha de Entrega"};
        String Datos [][]={};
        modelo=new DefaultTableModel(Datos,Cabecera);
        Tabla.setModel(modelo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TextoG = new javax.swing.JLabel();
        FalloEnlace = new javax.swing.JLabel();
        TextoFallo = new javax.swing.JLabel();
        ConExi = new javax.swing.JLabel();
        TextoExi = new javax.swing.JLabel();
        ImagenG = new javax.swing.JLabel();
        NoP = new javax.swing.JTextField();
        NP = new javax.swing.JTextField();
        NC = new javax.swing.JTextField();
        Producto = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        CodigoP = new javax.swing.JTextField();
        Tel = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        FA = new javax.swing.JLabel();
        FP = new javax.swing.JTextField();
        FE = new javax.swing.JTextField();
        Costo = new javax.swing.JTextField();
        CostoE = new javax.swing.JTextField();
        IVA = new javax.swing.JTextField();
        To = new javax.swing.JTextField();
        Can = new javax.swing.JComboBox();
        CanL = new javax.swing.JLabel();
        Envio = new javax.swing.JComboBox();
        EnvioL = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Otro = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Ope = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        Imagen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        Ayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 0, 48));
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Pedidos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 160, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Altas.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Altas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 70, 40));

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Bajas");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 70, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Bajas.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Consultas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Consultas.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Guardar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Guardar.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Actualizar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Actualizar.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/go-back64.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 620, -1, -1));

        Hora.setFont(new java.awt.Font("Viner Hand ITC", 0, 18));
        Hora.setForeground(new java.awt.Color(240, 240, 240));
        Hora.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora de Acceso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 140, 60));

        Fecha1.setFont(new java.awt.Font("Viner Hand ITC", 0, 18));
        Fecha1.setForeground(new java.awt.Color(240, 240, 240));
        Fecha1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de Acceso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 150, 60));

        Nombre2.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        Nombre2.setForeground(new java.awt.Color(240, 240, 240));
        Nombre2.setText("Registro");
        getContentPane().add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 350, 40));

        jLabel18.setFont(new java.awt.Font("Viner Hand ITC", 0, 36));
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Bienvenido");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 200, 60));

        TextoG.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        TextoG.setForeground(new java.awt.Color(240, 240, 240));
        TextoG.setText("Dato Agregado Exitosamente");
        getContentPane().add(TextoG, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 360, 330, -1));

        FalloEnlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Fallo Enlace.png"))); // NOI18N
        getContentPane().add(FalloEnlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 200, 140, -1));

        TextoFallo.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        TextoFallo.setForeground(new java.awt.Color(240, 240, 240));
        TextoFallo.setText("Error de enlace con la Base de Datos");
        getContentPane().add(TextoFallo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 370, 410, 30));

        ConExi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/ConsultaExitosa.png"))); // NOI18N
        getContentPane().add(ConExi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 210, -1, -1));

        TextoExi.setFont(new java.awt.Font("Viner Hand ITC", 0, 24));
        TextoExi.setForeground(new java.awt.Color(240, 240, 240));
        TextoExi.setText("Consulta Exitosa");
        getContentPane().add(TextoExi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, 200, 40));

        ImagenG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/AgregadoExi.png"))); // NOI18N
        getContentPane().add(ImagenG, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 200, 140, -1));

        NoP.setFont(new java.awt.Font("Arial", 0, 14));
        NoP.setForeground(new java.awt.Color(240, 240, 240));
        NoP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre del Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        NoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoPActionPerformed(evt);
            }
        });
        NoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NoPKeyTyped(evt);
            }
        });
        getContentPane().add(NoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 400, -1));

        NP.setFont(new java.awt.Font("Arial", 0, 14));
        NP.setForeground(new java.awt.Color(240, 240, 240));
        NP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Numero de Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        NP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NPKeyTyped(evt);
            }
        });
        getContentPane().add(NP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, -1));

        NC.setFont(new java.awt.Font("Arial", 0, 14));
        NC.setForeground(new java.awt.Color(240, 240, 240));
        NC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        NC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NCActionPerformed(evt);
            }
        });
        NC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NCKeyTyped(evt);
            }
        });
        getContentPane().add(NC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 400, -1));

        Producto.setFont(new java.awt.Font("Arial", 0, 14));
        Producto.setForeground(new java.awt.Color(240, 240, 240));
        Producto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoActionPerformed(evt);
            }
        });
        Producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ProductoKeyTyped(evt);
            }
        });
        getContentPane().add(Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 400, -1));

        Direccion.setFont(new java.awt.Font("Arial", 0, 14));
        Direccion.setForeground(new java.awt.Color(240, 240, 240));
        Direccion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionActionPerformed(evt);
            }
        });
        Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DireccionKeyTyped(evt);
            }
        });
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 400, -1));

        CodigoP.setFont(new java.awt.Font("Arial", 0, 14));
        CodigoP.setForeground(new java.awt.Color(240, 240, 240));
        CodigoP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Codigo Postal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        CodigoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoPKeyTyped(evt);
            }
        });
        getContentPane().add(CodigoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 190, -1));

        Tel.setFont(new java.awt.Font("Arial", 0, 14));
        Tel.setForeground(new java.awt.Color(240, 240, 240));
        Tel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelKeyTyped(evt);
            }
        });
        getContentPane().add(Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 190, -1));

        Email.setFont(new java.awt.Font("Arial", 0, 14));
        Email.setForeground(new java.awt.Color(240, 240, 240));
        Email.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Correo Electronico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EmailKeyTyped(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 400, -1));

        FA.setFont(new java.awt.Font("Viner Hand ITC", 0, 18));
        FA.setForeground(new java.awt.Color(240, 240, 240));
        FA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha Actual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(FA, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 150, 60));

        FP.setFont(new java.awt.Font("Arial", 0, 14));
        FP.setForeground(new java.awt.Color(240, 240, 240));
        FP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        FP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPActionPerformed(evt);
            }
        });
        getContentPane().add(FP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 140, -1));

        FE.setFont(new java.awt.Font("Arial", 0, 14));
        FE.setForeground(new java.awt.Color(240, 240, 240));
        FE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha Entrega", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        FE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEActionPerformed(evt);
            }
        });
        getContentPane().add(FE, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 140, -1));

        Costo.setFont(new java.awt.Font("Arial", 0, 14));
        Costo.setForeground(new java.awt.Color(240, 240, 240));
        Costo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Costo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        Costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoActionPerformed(evt);
            }
        });
        Costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CostoKeyTyped(evt);
            }
        });
        getContentPane().add(Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 140, -1));

        CostoE.setFont(new java.awt.Font("Arial", 0, 14));
        CostoE.setForeground(new java.awt.Color(240, 240, 240));
        CostoE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Costo de Envio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        CostoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoEActionPerformed(evt);
            }
        });
        CostoE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CostoEKeyTyped(evt);
            }
        });
        getContentPane().add(CostoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 140, -1));

        IVA.setFont(new java.awt.Font("Arial", 0, 14));
        IVA.setForeground(new java.awt.Color(240, 240, 240));
        IVA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Iva 16%", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        IVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IVAActionPerformed(evt);
            }
        });
        IVA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IVAKeyTyped(evt);
            }
        });
        getContentPane().add(IVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 140, -1));

        To.setFont(new java.awt.Font("Arial", 0, 14));
        To.setForeground(new java.awt.Color(240, 240, 240));
        To.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        To.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToActionPerformed(evt);
            }
        });
        To.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ToKeyTyped(evt);
            }
        });
        getContentPane().add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 140, -1));

        Can.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        Can.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanActionPerformed(evt);
            }
        });
        getContentPane().add(Can, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 80, 30));

        CanL.setFont(new java.awt.Font("Arial", 0, 24));
        CanL.setForeground(new java.awt.Color(240, 240, 240));
        CanL.setText("00");
        CanL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidad de Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(CanL, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 170, 50));

        Envio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Correo", "Terrestre", "Maritimo", "Aereo" }));
        Envio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnvioActionPerformed(evt);
            }
        });
        getContentPane().add(Envio, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 80, 30));

        EnvioL.setFont(new java.awt.Font("Arial", 0, 24));
        EnvioL.setForeground(new java.awt.Color(240, 240, 240));
        EnvioL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Envio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(240, 240, 240))); // NOI18N
        getContentPane().add(EnvioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 170, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/salir.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel17MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 620, -1, -1));

        Tabla.setBackground(new java.awt.Color(240, 240, 240));
        Tabla.setFont(new java.awt.Font("Arial", 0, 12));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Otro.setViewportView(Tabla);

        getContentPane().add(Otro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 1150, 140));

        Ope.setFont(new java.awt.Font("Arial", 0, 18));
        Ope.setForeground(new java.awt.Color(240, 240, 240));
        Ope.setText("Operacion");
        getContentPane().add(Ope, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, -1, -1));
        getContentPane().add(dateChooserCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, -1, -1));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpinteriacarso/imagenes/Fon5T.jpg"))); // NOI18N
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu3.setText("Archivo");

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Nuevo");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Actualizar");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu3);

        Ayuda.setText("Ayuda");
        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
     // Altas
        //Folio.disable();//DESHABILITAR LA CAJA DE TEXTO DE BUSCAR
        String O = JOptionPane.showInputDialog(rootPane, "Introduce la Accion a Realizar");
        Operacion = String.valueOf(String.valueOf(O));
        Ope.setText(String.valueOf(Operacion));
        int res = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
            new Clientes().setVisible(true);
        this.dispose();
        }
        if( res == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));
        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
        NP.setText("");
        //HABILITAR TODOS LOS TEXTFIELDS PARA EL INGRESO DE DATOS
        NoP.enable(true);
        NC.enable(true);
        Producto.enable(true);
        Direccion.enable(true);
        CodigoP.enable(true);
        Tel.enable(true);
        Email.enable(true);
        FP.enable(true);
        FE.enable(true);
        Costo.enable(true);
        CostoE.enable(true);
        IVA.enable(true);
        To.enable(true);
        CanL.enable(true);
        EnvioL.enable(true);
        Otro.setVisible(true);

                String NP1=NP.getText();
                String N=NC.getText();
                String No=NoP.getText();
                String Di=Direccion.getText();
                String Cod=CodigoP.getText();
                String Em=Email.getText();
                String Te=Tel.getText();
                String FP1=FP.getText();
                String FE1=FE.getText();
                String Co=Costo.getText();
                String CoE=CostoE.getText();
                String Ca=CanL.getText();
                String En=EnvioL.getText();
                String IV=IVA.getText();
                String T=To.getText();
                String H=Hora.getText();
                String Fe=Fecha1.getText();
                String No2=Nombre2.getText();
                String Op=Ope.getText();
               Object Datos[]={No2,Fe,H,Op,No,N,NP1,Di,T,FE1};
                modelo.addRow(Datos);

        //Se limpia cajas de texto
        NP.setText("");
        NoP.setText("");
        NC.setText("");
        Producto.setText("");
        Direccion.setText("");
        CodigoP.setText("");
        Tel.setText("");
        Email.setText("");
        FP.setText("");
        FE.setText("");
        Costo.setText("");
        CostoE.setText("");
        IVA.setText("");
        To.setText("");
        CanL.setText("");
        EnvioL.setText("");
            }
        }
}//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // Bajas
        try {
            Class.forName(  "com.mysql.jdbc.Driver" );
        } catch( Exception eve ) {
            JOptionPane.showMessageDialog(null,"Fallo Enlace, Sistema ");
            FalloEnlace.setVisible(true);
            TextoFallo.setVisible(true);
            ImagenG.setVisible(false);
        TextoG.setVisible(false);
        FalloEnlace.setVisible(false);
        ConExi.setVisible(false);
            return;
        }
        try{
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/cc","root", "123");
            sentencia=conexion.createStatement();

        String O = JOptionPane.showInputDialog(rootPane, "Introduce la Accion a Realizar");
        Operacion = String.valueOf(String.valueOf(O));
        Ope.setText(String.valueOf(Operacion));

       int res1 = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
       "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );

        if( res1 == JOptionPane.NO_OPTION ) {
        JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
        new Clientes().setVisible(true);
        this.dispose();
        }


        if( res1 == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));


        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");

             int res = JOptionPane.showConfirmDialog( this,"¿Esta Usted Seguro de dar de Baja",
             "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(null,"Baja Cancelada...!!!");
            sentencia.execute("DELETE FROM clientes WHERE Id_Cliente = "+NP.getText());
            sentencia.close();
        }
           if( res == JOptionPane.YES_OPTION ) {
               Otro.setVisible(true);
                 String NP1=NP.getText();
                String N=NC.getText();
                String No=NoP.getText();
                String Di=Direccion.getText();
                String Cod=CodigoP.getText();
                String Em=Email.getText();
                String Te=Tel.getText();
                String FP1=FP.getText();
                String FE1=FE.getText();
                String Co=Costo.getText();
                String CoE=CostoE.getText();
                String Ca=CanL.getText();
                String En=EnvioL.getText();
                String IV=IVA.getText();
                String T=To.getText();
                String H=Hora.getText();
                String Fe=Fecha1.getText();
                String No2=Nombre2.getText();
                String Op=Ope.getText();
                Object Datos[]={No2,Fe,H,Op,No,N,NP1,Di,T,FE1};
                modelo.addRow(Datos);

        //Se limpia cajas de texto
        NP.setText("");
        NoP.setText("");
        NC.setText("");
        Producto.setText("");
        Direccion.setText("");
        CodigoP.setText("");
        Tel.setText("");
        Email.setText("");
        FP.setText("");
        FE.setText("");
        Costo.setText("");
        CostoE.setText("");
        IVA.setText("");
        To.setText("");
        CanL.setText("");
        EnvioL.setText("");
            }}}
        } catch(SQLException x){JOptionPane.showMessageDialog(null,"Fallo Enlace, Sistema  ");
        FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
        }
}//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
         // Consultar

        try  {
            Class.forName( "com.mysql.jdbc.Driver" );
        } catch( Exception eve ) {
            JOptionPane.showMessageDialog(null,"Error en el Enlace, Sistema ");
            FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoFallo.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
            return;
        }
        try{
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/cc","root", "123");
            sentencia=conexion.createStatement();
             String O = JOptionPane.showInputDialog(rootPane, "Introduce la Accion a Realizar");
        Operacion = String.valueOf(String.valueOf(O));
        Ope.setText(String.valueOf(Operacion));
            int res = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
            new Clientes().setVisible(true);
        this.dispose();
        }
        if( res == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));
        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
            resultado=sentencia.executeQuery("SELECT * FROM pedidos WHERE NP =" + NP.getText());
            if (resultado.next()){


                NoP.setText(String.valueOf(resultado.getString(2)));
                NC.setText(String.valueOf(resultado.getString(3)));
                Producto.setText(String.valueOf(resultado.getString(4)));
                Direccion.setText(String.valueOf(resultado.getString(5)));
                CodigoP.setText(String.valueOf(resultado.getString(6)));
                Tel.setText(String.valueOf(resultado.getString(7)));
                Email.setText(String.valueOf(resultado.getString(8)));
                FP.setText(String.valueOf(resultado.getString(9)));
                FE.setText(String.valueOf(resultado.getString(10)));
                Costo.setText(String.valueOf(resultado.getString(11)));
                CostoE.setText(String.valueOf(resultado.getString(12)));
                IVA.setText(String.valueOf(resultado.getString(13)));
                To.setText(String.valueOf(resultado.getString(14)));
                CanL.setText(String.valueOf(resultado.getString(15)));
                EnvioL.setText(String.valueOf(resultado.getString(16)));
                Ope.setText(String.valueOf(resultado.getString(17)));
                Hora.setText(String.valueOf(resultado.getString(18)));
                Fecha1.setText(String.valueOf(resultado.getString(19)));
                Nombre2.setText(String.valueOf(resultado.getString(20)));

                String NP1=NP.getText();
                String N=NC.getText();
                String No=NoP.getText();
                String Di=Direccion.getText();
                String Cod=CodigoP.getText();
                String Em=Email.getText();
                String Te=Tel.getText();
                String FP1=FP.getText();
                String FE1=FE.getText();
                String Co=Costo.getText();
                String CoE=CostoE.getText();
                String Ca=CanL.getText();
                String En=EnvioL.getText();
                String IV=IVA.getText();
                String T=To.getText();
                String H=Hora.getText();
                String Fe=Fecha1.getText();
                String No2=Nombre2.getText();
                String Op=Ope.getText();
                Object Datos[]={No2,Fe,H,Op,No,N,NP1,Di,T,FE1};
                modelo.addRow(Datos);
//                Folio.setText("");
//                Nombre.setText("");
//            Edad.setText("");
//            Direccion.setText("");
//            RFC.setText("");
//            Email.setText("");
//            Telefono.setText("");
//            Promo.setText("");
//            Des.setText("");
//            Pago1.setText("");
//            Sexo.setText("");
                Otro.setVisible(true);
                TextoExi.setVisible(true);
                ConExi.setVisible(true);
                ImagenG.setVisible(false);
                TextoG.setVisible(false);
                FalloEnlace.setVisible(false);
                TextoFallo.setVisible(false);
                Tabla.setVisible(true);
                sentencia.close();
            } else {
                JOptionPane.showMessageDialog(null,"No existe el Pedido");
            }}}
        } catch(SQLException exp){
        JOptionPane.showMessageDialog(null,"Error en la Conexion, Sistema ");
        FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
        }
}//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // Guardar
if(NP.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo Numero de Pedido esta vacio");
 }
if(NoP.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo Nombre del Producto está vacío ");
 }
if(NC.getText().trim().length()==0)
 {
 JOptionPane.showMessageDialog(this, "El campo de Nombre de Cliente está vacío ");
 }
if(Producto.getText().trim().length()==0)
 {
 JOptionPane.showMessageDialog(this, "El campo de Producto está vacío ");
 }
if(Direccion.getText().trim().length()==0)
 {
 JOptionPane.showMessageDialog(this, "El campo de Direccion está vacío ");
 }
if(CodigoP.getText().trim().length()==0)
 {
 JOptionPane.showMessageDialog(this, "El campo de Codigo Postal está vacío ");
 }
if(Tel.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Telefono está vacío ");
 }
if(Email.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Email está vacío ");
 }
if(FP.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Fecha de Pedido está vacío ");
 }
if(FE.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Fecha de Entrega está vacío ");
 }
if(Costo.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Costo Unitario está vacío ");
 }
if(CostoE.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Costo de Envio está vacío ");
 }
if(IVA.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de IVA 16% está vacío ");
 }
if(To.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Total está vacío ");
 }
if(CanL.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Cantidad está vacío ");
 }
if(EnvioL.getText().trim().length()==0)
 {
       JOptionPane.showMessageDialog(this, "El campo de Envio está vacío ");
 }
        try {
            Class.forName(  "com.mysql.jdbc.Driver" );
        } catch( Exception eve ) {
            JOptionPane.showMessageDialog(null,"Fallo Enlace del Puente, Sistema"+eve);
            FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
            return;
        }
        if(NoP.getText()=="") {
            NoP.setText("");
        }
        if(NC.getText()=="") {
            NC.setText("");
        }
      if(Producto.getText()=="") {
            Producto.setText("");
        }
        if(Direccion.getText()=="") {
            Direccion.setText("");
        }
        if(CodigoP.getText()=="") {
            CodigoP.setText("");
        }
        if(Tel.getText()=="") {
            Tel.setText("");
        }
        if(Email.getText()=="") {
            Email.setText("");
        }
        if(FP.getText()=="") {
            FP.setText("");
        }
        if(FE.getText()=="") {
            FE.setText("");
        }
        if(Costo.getText()=="") {
            Costo.setText("");
        }
        if(CostoE.getText()=="") {
            CostoE.setText("");
        }
        if(IVA.getText()=="") {
            IVA.setText("");
        }
        if(To.getText()=="") {
            To.setText("");
        }
        if(CanL.getText()=="") {
            CanL.setText("");
        }
        if(EnvioL.getText()=="") {
            EnvioL.setText("");
        }
        if(Ope.getText()=="") {
            Ope.setText("");
        }
        if(Hora.getText()=="") {
            Hora.setText("");
        }
        if(Fecha1.getText()=="") {
            Fecha1.setText("");
        }
        if(Nombre2.getText()=="") {
            Nombre2.setText("");
        }

        try{
        String O = JOptionPane.showInputDialog(rootPane, "Introduce la Accion a Realizar");
        Operacion = String.valueOf(String.valueOf(O));
        Ope.setText(String.valueOf(Operacion));
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/cc","root", "123");
            sentencia=conexion.createStatement();
            sentencia.executeUpdate("INSERT INTO pedidos"+
                    " VALUES ('"+NP.getText()+"',"+
                    "'"+NoP.getText()+"',"+
                    "'"+NC.getText()+"',"+
                    "'"+Producto.getText()+"',"+
                    "'"+Direccion.getText()+"',"+
                    "'"+CodigoP.getText()+"',"+
                    "'"+Tel.getText()+"',"+
                    "'"+Email.getText()+"',"+
                    "'"+FP.getText()+"',"+
                    "'"+FE.getText()+"',"+
                    "'"+Costo.getText()+"',"+
                    "'"+CostoE.getText()+"',"+
                    "'"+IVA.getText()+"',"+
                    "'"+To.getText()+"',"+
                    "'"+CanL.getText()+"',"+
                    "'"+EnvioL.getText()+"',"+
                    "'"+Ope.getText()+"',"+
                    "'"+Hora.getText()+"',"+
                    "'"+Fecha1.getText()+"',"+
                    "'"+Nombre2.getText()+"')");
            
                Otro.setVisible(true);
                String NP1=NP.getText();
                String N=NC.getText();
                String No=NoP.getText();
                String Di=Direccion.getText();
                String Cod=CodigoP.getText();
                String Em=Email.getText();
                String Te=Tel.getText();
                String FP1=FP.getText();
                String FE1=FE.getText();
                String Co=Costo.getText();
                String CoE=CostoE.getText();
                String Ca=CanL.getText();
                String En=EnvioL.getText();
                String IV=IVA.getText();
                String T=To.getText();
                String H=Hora.getText();
                String Fe=Fecha1.getText();
                String No2=Nombre2.getText();
                String Op=Ope.getText();
                Object Datos[]={No2,Fe,H,Op,No,N,NP1,Di,T,FE1};
                modelo.addRow(Datos);

        //Se limpia cajas de texto
        NP.setText("");
        NoP.setText("");
        NC.setText("");
        Producto.setText("");
        Direccion.setText("");
        CodigoP.setText("");
        Tel.setText("");
        Email.setText("");
        FP.setText("");
        FE.setText("");
        Costo.setText("");
        CostoE.setText("");
        IVA.setText("");
        To.setText("");
        CanL.setText("");
        EnvioL.setText("");

            conexion.close();
            JOptionPane.showMessageDialog(null,"Pedido Guardado ");
            ImagenG.setVisible(true);
        TextoG.setVisible(true);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
         FalloEnlace.setVisible(false);
        TextoFallo.setVisible(false);
        } catch(SQLException p){ JOptionPane.showMessageDialog(null,"Error en el enlace, Sistema"+p);
        FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);}

//        //LIMPIAR CAJA DE TEXTO UNA VEZ GUARDADA LA INFORMACION.
//         Folio.setText("");
//         Nombre.setText("");
//         IniciodeOperacion.setText("");
//         Edad.setText("");
//         Sexo.setText("");
//         Puesto.setText("");
//         Salario.setText("");
//         CP.setText("");
//         Calle.setText("");
//         Colonia.setText("");
//         Mz.setText("");
//         Lt.setText("");
//         TP.setText("");
//         TC.setText("");
//         TR.setText("");
//         Email.setText("");
//         curp.setText("");
//        //HABILITAR LA CAJA DE TEXTO DE BUSCAR.
        NP.enable();
}//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
      try  {
            Class.forName( "com.mysql.jdbc.Driver" );
        } catch( Exception eve ) {
            JOptionPane.showMessageDialog(null,"Error en el Enlace, Sistema ");
            FalloEnlace.setVisible(true);
            TextoFallo.setVisible(true);
            ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
            return;
        }
        try{
            conexion=DriverManager.getConnection("jdbc:mysql://localhost/cc","root", "123");
            sentencia=conexion.createStatement();
             String O = JOptionPane.showInputDialog(rootPane, "Introduce la Accion a Realizar");
        Operacion = String.valueOf(String.valueOf(O));
        Ope.setText(String.valueOf(Operacion));
             int res = JOptionPane.showConfirmDialog( this,"¿Usted es Administrador",
                "Sistema Farmacia Alex",JOptionPane.YES_NO_OPTION );
        if( res == JOptionPane.NO_OPTION ) {
            JOptionPane.showMessageDialog(rootPane,"Acceso Denegado");
            new Clientes().setVisible(true);
        this.dispose();
        }
        if( res == JOptionPane.YES_OPTION ) {
        String Nom = JOptionPane.showInputDialog(rootPane,"Introduce tu Usuario");
        Nombre1 = String.valueOf(String.valueOf(Nom));
        String Con = JOptionPane.showInputDialog(rootPane,"Introduce tu Contaseña");
        Contrasena= Integer.parseInt(String.valueOf(Con));
        if(Nom.equals("Joel")&& Con.equals("123") ){
            JOptionPane.showMessageDialog(rootPane,"Contraseña Correcta");
            sentencia.execute("UPDATE pedidos SET "
                    + "Nop=("+NoP.getText()+"),"
                    + "NC=('"+NC.getText()+"'),"
                    + "Producto=('"+Producto.getText()+"'),"
                    + "Direccion=('"+Direccion.getText()+"'),"
                    + "CodigoP=("+CodigoP.getText()+"),"
                    + "Tel=('"+Tel.getText()+"'),"
                    + "Email=('"+Email.getText()+"'),"
                    + "FP=('"+FP.getText()+"'),"
                    + "FP=('"+FP.getText()+"'),"
                    + "Costo=('"+Costo.getText()+"'),"
                    + "CostoE=('"+CostoE.getText()+"'),"
                    + "IVA=('"+IVA.getText()+"'),"
                    + "To=('"+To.getText()+"'),"
                    + "CanL=('"+CanL.getText()+"'),"
                    + "EnvioL=('"+EnvioL.getText()+"'),"
                    + "Ope=('"+Ope.getText()+"'),"
                    + "Hora=('"+Hora.getText()+"'),"
                    + "Fecha1=('"+Fecha1.getText()+"'),"
                    + "FE=('"+Nombre2.getText()+"')"
                    + " WHERE Id_Cliente=" + NP.getText());
            Otro.setVisible(true);
             String NP1=NP.getText();
                String N=NC.getText();
                String No=NoP.getText();
                String Di=Direccion.getText();
                String Cod=CodigoP.getText();
                String Em=Email.getText();
                String Te=Tel.getText();
                String FP1=FP.getText();
                String FE1=FE.getText();
                String Co=Costo.getText();
                String CoE=CostoE.getText();
                String Ca=CanL.getText();
                String En=EnvioL.getText();
                String IV=IVA.getText();
                String T=To.getText();
                String H=Hora.getText();
                String Fe=Fecha1.getText();
                String No2=Nombre2.getText();
                String Op=Ope.getText();
                Object Datos[]={No2,Fe,H,Op,No,N,NP1,Di,T,FE1};
                modelo.addRow(Datos);

            JOptionPane.showMessageDialog(null,"Cambios Realizados, Registro Guardado ");
        }}
            sentencia.close();
        } catch (SQLException e2){
            JOptionPane.showMessageDialog(null,"Fallo Enlace, Sistema "+e2);
         FalloEnlace.setVisible(true);
        TextoFallo.setVisible(true);
        ImagenG.setVisible(false);
        TextoG.setVisible(false);
        TextoExi.setVisible(false);
        ConExi.setVisible(false);
        }
}//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        new Menu().setVisible(true);
        this.dispose();
}//GEN-LAST:event_jLabel15MouseClicked

    private void FPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FPActionPerformed

    private void FEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FEActionPerformed

    private void CostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoActionPerformed

    private void CostoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoEActionPerformed

    private void IVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IVAActionPerformed

    private void ToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        int res = JOptionPane.showConfirmDialog(this, "¿Esta Usted Seguro de Salir del Sistema Carpiteria Carso?",
                "Sistema Farmacia Alex", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "Gracias por usar el Sistema");
            new Salir().setVisible(true);
            this.dispose();
        }
}//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseReleased
        // TODO add your handling code here:
}//GEN-LAST:event_jLabel17MouseReleased

    private void NPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NPKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        NP.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 10;
            public void keyTyped(KeyEvent e) {
                if (NP.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_NPKeyTyped

    private void CostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CostoKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        Costo.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 10;
            public void keyTyped(KeyEvent e) {
                if (Costo.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_CostoKeyTyped

    private void CostoEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CostoEKeyTyped
         char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
         CostoE.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 10;
            public void keyTyped(KeyEvent e) {
                if (CostoE.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_CostoEKeyTyped

    private void IVAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IVAKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        IVA.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 5;
            public void keyTyped(KeyEvent e) {
                if (IVA.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_IVAKeyTyped

    private void ToKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ToKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        To.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 8;
            public void keyTyped(KeyEvent e) {
                if (To.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_ToKeyTyped

    private void TelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        Tel.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 10;
            public void keyTyped(KeyEvent e) {
                if (Tel.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_TelKeyTyped

    private void CodigoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoPKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9') {
            getToolkit().beep();
            evt.consume();
        }
        CodigoP.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 5;
            public void keyTyped(KeyEvent e) {
                if (CodigoP.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_CodigoPKeyTyped

    private void NoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoPKeyTyped
       char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE)) evt.consume(); getToolkit().beep();
       NoP.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 15;
            public void keyTyped(KeyEvent e) {
                if (NoP.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_NoPKeyTyped

    private void NCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NCKeyTyped
       char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE)) evt.consume();getToolkit().beep();
NC.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 15;
            public void keyTyped(KeyEvent e) {
                if (NC.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_NCKeyTyped

    private void ProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ProductoKeyTyped
        char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE)) evt.consume(); getToolkit().beep();
Producto.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 15;
            public void keyTyped(KeyEvent e) {
                if (Producto.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_ProductoKeyTyped

    private void DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyTyped
        char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE)) evt.consume(); getToolkit().beep();
Direccion.addKeyListener((KeyListener) new KeyListener(){

            int limite  = 15;
            public void keyTyped(KeyEvent e) {
                if (Direccion.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_DireccionKeyTyped

    private void EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailKeyTyped
      char c= evt.getKeyChar();
if((c<'a'||c>'z') && (c<'!' || c>'.') && (c!=(char)KeyEvent.VK_SPACE)) getToolkit().beep();
      Email.addKeyListener((KeyListener) new KeyListener(){
            int limite  = 15;
            public void keyTyped(KeyEvent e) {
                if (Email.getText().length()== limite){
                    getToolkit().beep();
                    e.consume();}
            }
            public void keyPressed(KeyEvent arg0) {
            }
            public void keyReleased(KeyEvent arg0) {
            }});
    }//GEN-LAST:event_EmailKeyTyped

    private void CanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanActionPerformed
        if(Can.getSelectedIndex()==0){
          CanL.setText(String.valueOf("0"));
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma;
         
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
         if(Can.getSelectedIndex()==1){
          CanL.setText(String.valueOf("1"));
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma;
          
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
         if(Can.getSelectedIndex()==2){
          CanL.setText(String.valueOf("2"));
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma;
          
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
         if(Can.getSelectedIndex()==3){
          CanL.setText(String.valueOf("3"));
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma;
          
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
         if(Can.getSelectedIndex()==4){
          CanL.setText(String.valueOf("4"));
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma;
         
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
         if(Can.getSelectedIndex()==5){
          CanL.setText(String.valueOf("5"));
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma;
          
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
         if(Can.getSelectedIndex()==6){
          CanL.setText(String.valueOf("6"));
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma;
         
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
         if(Can.getSelectedIndex()==7){
          CanL.setText(String.valueOf("7"));
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma;
         
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
         if(Can.getSelectedIndex()==8){
          CanL.setText(String.valueOf("8"));
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma;
          
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
         if(Can.getSelectedIndex()==9){
          CanL.setText(String.valueOf("9"));
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma;
          
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
         if(Can.getSelectedIndex()==10){
          CanL.setText(String.valueOf("10"));
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma;
          
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
    }//GEN-LAST:event_CanActionPerformed

    private void EnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnvioActionPerformed
       if(Envio.getSelectedIndex()==0){
          EnvioL.setText(String.valueOf("Correo"));
          CostoE.setText(String.valueOf("1500"));
          int CostE=Integer.parseInt(CostoE.getText());
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma+CostE;
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
       if(Envio.getSelectedIndex()==1){
          EnvioL.setText(String.valueOf("Terrestre"));
          CostoE.setText(String.valueOf("2500"));
          int CostE=Integer.parseInt(CostoE.getText());
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma+CostE;
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
       if(Envio.getSelectedIndex()==2){
          EnvioL.setText(String.valueOf("Maritimo"));
          CostoE.setText(String.valueOf("3500"));
          int CostE=Integer.parseInt(CostoE.getText());
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma+CostE;
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
       if(Envio.getSelectedIndex()==3){
          EnvioL.setText(String.valueOf("Aereo"));
          CostoE.setText(String.valueOf("5500"));
          int CostE=Integer.parseInt(CostoE.getText());
          int Can=Integer.parseInt(CanL.getText());
          int Cos=Integer.parseInt(Costo.getText());
          int Suma=(Cos*Can);
          Double iva=Suma*0.16;
          Double Total=iva+Suma+CostE;
          IVA.setText(String.valueOf(iva));
          To.setText(String.valueOf(Total));
      }
    }//GEN-LAST:event_EnvioActionPerformed

    private void NoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoPActionPerformed
        String Cadena = NoP.getText();
        NoP.setText(Cadena.toUpperCase());
    }//GEN-LAST:event_NoPActionPerformed

    private void NCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NCActionPerformed
        String Cadena = NC.getText();
        NC.setText(Cadena.toUpperCase());
    }//GEN-LAST:event_NCActionPerformed

    private void ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoActionPerformed
        String Cadena = Producto.getText();
        Producto.setText(Cadena.toUpperCase());
    }//GEN-LAST:event_ProductoActionPerformed

    private void DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionActionPerformed
      String Cadena = Direccion.getText();
        Direccion.setText(Cadena.toUpperCase());
    }//GEN-LAST:event_DireccionActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
      String Cadena = Email.getText();
        Email.setText(Cadena.toUpperCase());
    }//GEN-LAST:event_EmailActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        new Pedidos().setVisible(true);
        this.dispose();
}//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        new Pedidos().setVisible(true);
        this.dispose();
}//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JComboBox Can;
    private javax.swing.JLabel CanL;
    private javax.swing.JTextField CodigoP;
    private javax.swing.JLabel ConExi;
    private javax.swing.JTextField Costo;
    private javax.swing.JTextField CostoE;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Email;
    private javax.swing.JComboBox Envio;
    private javax.swing.JLabel EnvioL;
    private javax.swing.JLabel FA;
    private javax.swing.JTextField FE;
    private javax.swing.JTextField FP;
    private javax.swing.JLabel FalloEnlace;
    private javax.swing.JLabel Fecha1;
    private javax.swing.JLabel Hora;
    private javax.swing.JTextField IVA;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel ImagenG;
    private javax.swing.JTextField NC;
    private javax.swing.JTextField NP;
    private javax.swing.JTextField NoP;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Ope;
    private javax.swing.JScrollPane Otro;
    private javax.swing.JTextField Producto;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField Tel;
    private javax.swing.JLabel TextoExi;
    private javax.swing.JLabel TextoFallo;
    private javax.swing.JLabel TextoG;
    private javax.swing.JTextField To;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

}
